"""
Executive Briefing Models — LLM-Synthesized Strategy Briefings

Stores executive briefings generated by Claude Sonnet (or vLLM fallback)
from platform metrics, along with follow-up Q&A and scheduling config.

Inspired by van Schalkwyk's "Sunday Morning Strategy" approach:
scout agents gather data → LLM synthesizes → scored recommendations → team shares.
"""

from datetime import datetime
from typing import Optional, List
import enum

from sqlalchemy import (
    Column, Integer, String, DateTime, ForeignKey, JSON,
    Boolean, Float, Enum as SAEnum, Index, Text, UniqueConstraint
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from .base import Base


class BriefingType(str, enum.Enum):
    """Type/cadence of briefing."""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    ADHOC = "adhoc"


class BriefingStatus(str, enum.Enum):
    """Generation status lifecycle."""
    PENDING = "pending"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


class ExecutiveBriefing(Base):
    """
    Primary table storing each executive briefing.

    Contains the raw data pack (metrics snapshot), LLM-generated narrative,
    scored recommendations, and generation metadata.
    """
    __tablename__ = "executive_briefings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Scope
    tenant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False, index=True
    )
    requested_by: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )

    # Type and status (stored as lowercase strings to match migration schema)
    briefing_type: Mapped[str] = mapped_column(
        String(20), nullable=False, default="adhoc", index=True
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending", index=True
    )

    # Content
    title: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    data_pack: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    narrative: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    recommendations: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    executive_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # LLM metadata
    model_used: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    tokens_used: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    generation_time_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    kb_context_used: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Relationships
    followups: Mapped[List["BriefingFollowup"]] = relationship(
        "BriefingFollowup", back_populates="briefing",
        cascade="all, delete-orphan", order_by="BriefingFollowup.created_at"
    )

    __table_args__ = (
        Index("ix_exec_briefing_tenant_created", "tenant_id", "created_at"),
    )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "tenant_id": self.tenant_id,
            "requested_by": self.requested_by,
            "briefing_type": self.briefing_type.value if isinstance(self.briefing_type, BriefingType) else self.briefing_type,
            "status": self.status.value if isinstance(self.status, BriefingStatus) else self.status,
            "title": self.title,
            "data_pack": self.data_pack,
            "narrative": self.narrative,
            "recommendations": self.recommendations,
            "executive_summary": self.executive_summary,
            "model_used": self.model_used,
            "tokens_used": self.tokens_used,
            "generation_time_ms": self.generation_time_ms,
            "kb_context_used": self.kb_context_used,
            "error_message": self.error_message,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "followups": [f.to_dict() for f in self.followups] if self.followups else [],
        }


class BriefingFollowup(Base):
    """
    Follow-up Q&A attached to a briefing.

    Enables interactive "Ask the Briefing" drill-down.
    """
    __tablename__ = "briefing_followups"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    briefing_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("executive_briefings.id", ondelete="CASCADE"),
        nullable=False, index=True
    )
    asked_by: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )

    # Content
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # LLM metadata
    model_used: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    tokens_used: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )

    # Relationships
    briefing: Mapped["ExecutiveBriefing"] = relationship(
        "ExecutiveBriefing", back_populates="followups"
    )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "briefing_id": self.briefing_id,
            "asked_by": self.asked_by,
            "question": self.question,
            "answer": self.answer,
            "model_used": self.model_used,
            "tokens_used": self.tokens_used,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class BriefingSchedule(Base):
    """
    Per-tenant schedule configuration for automated briefing generation.

    One schedule per tenant (unique constraint on tenant_id).
    """
    __tablename__ = "briefing_schedules"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    tenant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False, unique=True
    )

    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    briefing_type: Mapped[str] = mapped_column(
        SAEnum(BriefingType, name="briefing_type_enum", create_constraint=False),
        nullable=False, default=BriefingType.WEEKLY
    )

    # Cron fields
    cron_day_of_week: Mapped[str] = mapped_column(
        String(10), nullable=False, default="mon"
    )
    cron_hour: Mapped[int] = mapped_column(Integer, nullable=False, default=6)
    cron_minute: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "tenant_id": self.tenant_id,
            "enabled": self.enabled,
            "briefing_type": self.briefing_type.value if isinstance(self.briefing_type, BriefingType) else self.briefing_type,
            "cron_day_of_week": self.cron_day_of_week,
            "cron_hour": self.cron_hour,
            "cron_minute": self.cron_minute,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
