"""
GNN Directive Review — Human Override Capture at Network Level

Persists tGNNSiteDirectives and S&OP GraphSAGE outputs with
human review/override tracking. Enables the same Bayesian override
effectiveness analysis for GNN-level decisions (not just TRMs).

Three review scopes:
    1. S&OP Policy Parameters — safety_stock_multiplier, criticality_score,
       bottleneck_risk, resilience_score (weekly cadence)
    2. Execution Directives — demand_forecast, exception_probability,
       order_recommendation (daily cadence)
    3. Allocation Refreshes — priority allocations from tGNN (daily)

See docs/OVERRIDE_EFFECTIVENESS_METHODOLOGY.md Section 11.
"""

from datetime import datetime

from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Text, Boolean, JSON,
    ForeignKey, Index,
)
from sqlalchemy.sql import func

from app.db.base_class import Base


class GNNDirectiveReview(Base):
    """
    Persisted tGNN directive with human review/override tracking.

    Each row represents one tGNNSiteDirective generated by the GNN
    orchestration cycle. Starts as PROPOSED (INFORMED in AIIO model);
    humans can Action, Inspect, or Override before the directive is
    applied to the SiteAgent.

    Override fields feed into the OverrideEffectivenessService Bayesian
    posteriors with tier-appropriate signal strength.
    """
    __tablename__ = "gnn_directive_reviews"

    id = Column(Integer, primary_key=True, index=True)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False)
    site_key = Column(String(64), nullable=False, index=True)
    directive_scope = Column(String(30), nullable=False, index=True)
    # scope: "sop_policy" | "execution_directive" | "allocation_refresh"

    # GNN-generated values (proposed)
    proposed_values = Column(JSON, nullable=False)
    # For sop_policy: {safety_stock_multiplier, criticality_score, bottleneck_risk, ...}
    # For execution_directive: {demand_forecast, exception_probability, ...}
    # For allocation_refresh: {allocation_version, priority_allocations, ...}

    # Plain-English reasoning for the proposed values (from GNN reasoning generators)
    proposed_reasoning = Column(Text, nullable=True)

    # Model metadata
    model_type = Column(String(30))  # "sop_graphsage" | "execution_tgnn"
    model_confidence = Column(Float)
    checkpoint_path = Column(String(512))

    # Review status (DB values; mapped to AIIO names in to_dict())
    status = Column(String(20), default="PROPOSED", index=True)
    # DB: PROPOSED | ACCEPTED | INSPECTED | OVERRIDDEN | AUTO_APPLIED | EXPIRED
    # AIIO (frontend): INFORMED | ACTIONED | INSPECTED | OVERRIDDEN

    # Human override
    reviewed_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    override_values = Column(JSON, nullable=True)
    # What the human changed — same structure as proposed_values
    override_reason_code = Column(String(50), nullable=True)
    override_reason_text = Column(Text, nullable=True)

    # Outcome tracking (filled by OutcomeCollector after feedback horizon)
    applied_at = Column(DateTime, nullable=True)
    outcome_measured_at = Column(DateTime, nullable=True)
    proposed_outcome_metric = Column(Float, nullable=True)
    # Metric achieved if GNN proposal had been followed (counterfactual)
    actual_outcome_metric = Column(Float, nullable=True)
    # Metric achieved with what was actually applied
    override_delta = Column(Float, nullable=True)
    # actual - proposed (positive = human was right)
    override_classification = Column(String(20), nullable=True)
    # BENEFICIAL | NEUTRAL | DETRIMENTAL

    # ── Vertical Urgency Propagation ────────────────────────────────────
    # GNN urgency is NOT computed independently — it aggregates and amplifies
    # execution-level signals that couldn't be resolved locally.
    #
    # Example flow:
    #   Layer 1 TRM: MO agent sees 95% OEE for 3 weeks → CAPACITY_STRESS signal
    #   Layer 1.5 Site tGNN: Evaluates shift extension → guardrail blocks (min 4 weeks)
    #     → emits CAPACITY_CONSTRAINED_ESCALATION upward
    #   Layer 2 Network tGNN: Sees escalation + demand risk → urgency HIGH
    #     → proposes inventory rebalance from another site
    #
    # The propagated_urgency captures WHY this GNN decision is urgent,
    # tracing back to the execution-level observations that triggered it.

    # Decision level within the Powell hierarchy
    decision_level = Column(String(20), nullable=True)
    # "strategic" (S&OP GraphSAGE) | "tactical" (Execution tGNN) | "operational" (Site tGNN)

    # Propagated urgency: computed from lower-level signals, not just model output
    propagated_urgency = Column(Float, nullable=True)
    # 0-1 score: weighted combination of escalation severity + local resolution failure + revenue at risk

    # Source escalation that triggered this GNN action (if any)
    escalation_id = Column(Integer, ForeignKey("powell_escalation_log.id", ondelete="SET NULL"), nullable=True)

    # Lower-level signals that fed into this decision (JSON array)
    # Each entry: {trm_type, signal_type, site_key, urgency, observation, duration_hours}
    source_signals = Column(JSON, nullable=True)
    # Example: [
    #   {"trm_type": "mo_execution", "signal_type": "CAPACITY_STRESS",
    #    "site_key": "1710", "urgency": 0.85, "observation": "OEE 95% for 21 days",
    #    "duration_hours": 504},
    #   {"trm_type": "atp_executor", "signal_type": "FILL_RATE_DEGRADATION",
    #    "site_key": "1710", "urgency": 0.72, "observation": "Fill rate dropped 98% → 91%",
    #    "duration_hours": 168}
    # ]

    # Whether local resolution was attempted and failed (escalation reason)
    local_resolution_attempted = Column(Boolean, default=False)
    local_resolution_blocked_by = Column(String(200), nullable=True)
    # e.g. "Guardrail: minimum shift extension period is 4 weeks"
    #      "Capacity: no available capacity at site for next 2 weeks"
    #      "Authority: cross-site transfer requires MPS_MANAGER approval"

    # Revenue/cost impact that elevated this from routine to urgent
    revenue_at_risk = Column(Float, nullable=True)  # $ at risk if not acted on
    cost_of_delay_per_day = Column(Float, nullable=True)  # $/day incremental cost

    # Timestamps
    created_at = Column(DateTime, server_default=func.now())
    expires_at = Column(DateTime, nullable=True)
    # If not reviewed by expires_at, auto-apply or expire

    __table_args__ = (
        Index("idx_gnn_review_site_scope", "site_key", "directive_scope"),
        Index("idx_gnn_review_status", "status", "created_at"),
        Index("idx_gnn_review_override", "override_classification"),
    )

    # Map DB status values to AIIO frontend names
    _DB_TO_AIIO = {
        "PROPOSED": "INFORMED",
        "ACCEPTED": "ACTIONED",
        "INSPECTED": "INSPECTED",
        "OVERRIDDEN": "OVERRIDDEN",
        "AUTO_APPLIED": "ACTIONED",
        "EXPIRED": "ACTIONED",
        "REJECTED": "OVERRIDDEN",
    }

    def to_dict(self):
        return {
            "id": self.id,
            "config_id": self.config_id,
            "site_key": self.site_key,
            "directive_scope": self.directive_scope,
            "decision_level": self.decision_level,
            "proposed_values": self.proposed_values,
            "proposed_reasoning": self.proposed_reasoning,
            "model_type": self.model_type,
            "model_confidence": self.model_confidence,
            # Vertical urgency propagation
            "propagated_urgency": self.propagated_urgency,
            "source_signals": self.source_signals,
            "local_resolution_attempted": self.local_resolution_attempted,
            "local_resolution_blocked_by": self.local_resolution_blocked_by,
            "revenue_at_risk": self.revenue_at_risk,
            "cost_of_delay_per_day": self.cost_of_delay_per_day,
            "escalation_id": self.escalation_id,
            # AIIO status
            "status": self._DB_TO_AIIO.get(self.status, self.status),
            "reviewed_by": self.reviewed_by,
            "reviewed_at": self.reviewed_at.isoformat() if self.reviewed_at else None,
            "override_values": self.override_values,
            "override_reason_code": self.override_reason_code,
            "override_reason_text": self.override_reason_text,
            "override_delta": self.override_delta,
            "override_classification": self.override_classification,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
        }


class PolicyEnvelopeOverride(Base):
    """
    Human override of S&OP Policy Envelope parameters.

    When S&OP GraphSAGE generates policy parameters (safety stock targets,
    OTIF floors, allocation reserves), the S&OP Director can override
    individual parameters before they propagate downstream.

    Each row captures one override of one parameter within a PolicyEnvelope.
    """
    __tablename__ = "policy_envelope_overrides"

    id = Column(Integer, primary_key=True, index=True)

    # Link to the PolicyEnvelope
    policy_envelope_id = Column(Integer, ForeignKey("planning_policy_envelope.id"), nullable=False)
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False)

    # What was changed
    parameter_path = Column(String(100), nullable=False)
    # e.g., "safety_stock_targets.frozen", "otif_floors.strategic", "expedite_caps.frozen"
    original_value = Column(JSON, nullable=False)  # GNN/system proposed
    override_value = Column(JSON, nullable=False)  # Human chose

    # Override metadata
    override_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    override_at = Column(DateTime, server_default=func.now())
    reason_code = Column(String(50), nullable=True)
    reason_text = Column(Text, nullable=True)

    # Outcome (filled later)
    outcome_delta = Column(Float, nullable=True)
    outcome_classification = Column(String(20), nullable=True)

    created_at = Column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("idx_pe_override_envelope", "policy_envelope_id"),
        Index("idx_pe_override_param", "parameter_path"),
    )

    def to_dict(self):
        return {
            "id": self.id,
            "policy_envelope_id": self.policy_envelope_id,
            "parameter_path": self.parameter_path,
            "original_value": self.original_value,
            "override_value": self.override_value,
            "override_by": self.override_by,
            "override_at": self.override_at.isoformat() if self.override_at else None,
            "reason_code": self.reason_code,
            "reason_text": self.reason_text,
            "outcome_delta": self.outcome_delta,
            "outcome_classification": self.outcome_classification,
        }
