"""
Planning Cascade Models

Full cascade from S&OP through Supply Commit and Allocation Commit.
Supports both FULL mode (with S&OP/MPS layers) and INPUT mode (agents only).

Based on:
- FG Supply Planning as AI Labor.pdf
- Integrated Supply Planning as AI Labor.pdf
- Powell SDAM Framework

Feed-Forward Contracts:
- Each layer produces versioned, hashable artifacts
- Artifacts become grounding input for downstream layers
- Preserves decision identity and reproducibility

Feed-Back Signals:
- Outcome signals re-tune upstream policy parameters
- Enables continuous improvement loop
"""

from datetime import datetime, date
from typing import Optional, Dict, Any, List
import hashlib
import json
import enum

from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Date, Text, Boolean, JSON,
    ForeignKey, Index, Enum
)
from sqlalchemy.orm import relationship

from .base import Base  # Must use same Base as other models (supply_chain_config, etc.)


# =============================================================================
# Enums
# =============================================================================

class PolicySource(str, enum.Enum):
    """Source of policy parameters"""
    AUTONOMY_SIM = "autonomy_sim"      # Generated by Autonomy S&OP simulation
    CUSTOMER_INPUT = "customer_input"   # Manually entered by customer
    SYSTEM_DEFAULT = "system_default"   # System defaults


class LayerName(str, enum.Enum):
    """Sellable cascade layers"""
    SOP = "sop"                        # S&OP Strategic Planning
    MRS = "mrs"                        # Supply Baseline Layer (unified — BOM explosion conditional on topology)
    SUPPLY_AGENT = "supply_agent"      # Supply Agent (Supply Commit)
    ALLOCATION_AGENT = "allocation_agent"  # Allocation Agent (Allocation Commit)
    EXECUTION = "execution"            # Execution (Foundation + TRM)


class LayerMode(str, enum.Enum):
    """Operating mode for a layer"""
    ACTIVE = "active"     # Layer purchased and AI-driven
    INPUT = "input"       # Customer provides manual input
    DISABLED = "disabled" # Layer not available


class CandidateMethod(str, enum.Enum):
    """Methods for generating supply plan candidates"""
    REORDER_POINT = "REORDER_POINT_V1"       # Classic (R, Q) policy
    PERIODIC_REVIEW = "PERIODIC_REVIEW_V1"    # (s, S) policy
    MIN_COST_EOQ = "MIN_COST_EOQ_V1"         # EOQ-based ordering
    SERVICE_MAXIMIZED = "SERVICE_MAXIMIZED_V1"  # Maximize fill rate
    PARAMETRIC_CFA = "PARAMETRIC_CFA_V1"     # Powell CFA with learned θ
    MRP_STANDARD = "MRP_STANDARD_V1"         # Standard MRP explosion
    SAFETY_STOCK_OPT = "SAFETY_STOCK_OPTIMIZED_V1"  # Safety stock optimized
    CUSTOMER_UPLOAD = "CUSTOMER_UPLOAD"       # Customer's own plan


class AllocationMethod(str, enum.Enum):
    """Methods for generating allocation candidates"""
    FAIR_SHARE = "FAIR_SHARE_V1"           # Proportional allocation
    PRIORITY_HEURISTIC = "PRIORITY_V1"      # Priority-based allocation
    LP_OPTIMAL = "LP_OPTIMAL_V1"            # Linear programming
    MILP_OPTIMAL = "MILP_OPTIMAL_V1"        # Mixed-integer LP
    HYBRID = "HYBRID_V1"                    # Hybrid approach


class CommitStatus(str, enum.Enum):
    """Status of Supply/Allocation Commit"""
    PROPOSED = "proposed"        # Agent proposed, awaiting review
    REVIEWED = "reviewed"        # User reviewed
    ACCEPTED = "accepted"        # Accepted without changes
    OVERRIDDEN = "overridden"    # User made changes
    SUBMITTED = "submitted"      # Submitted for execution
    AUTO_SUBMITTED = "auto_submitted"  # Auto-submitted (autonomous mode)
    REJECTED = "rejected"        # Rejected


class IntegrityViolationType(str, enum.Enum):
    """Types of integrity violations (block submission)"""
    NEGATIVE_INVENTORY = "negative_inventory"
    LEAD_TIME_INFEASIBLE = "lead_time_infeasible"
    MOQ_VIOLATION = "moq_violation"
    DEMAND_UNCOVERED = "demand_uncovered"
    SUPPLY_CONSERVATION = "supply_conservation"
    TEMPORAL_INFEASIBLE = "temporal_infeasible"


class RiskFlagType(str, enum.Enum):
    """Types of risk flags (mark suggested)"""
    SERVICE_RISK = "service_risk"           # OTIF below floor
    INVENTORY_INVESTMENT = "inventory_investment"  # DOS exceeds ceiling
    SUPPLIER_CONCENTRATION = "supplier_concentration"  # Single-source too high
    EXPEDITE_EXPOSURE = "expedite_exposure"  # Expedite spend too high
    EO_EXPOSURE = "eo_exposure"             # E&O risk too high
    PLAN_STABILITY = "plan_stability"       # Period-over-period whiplash


# =============================================================================
# S&OP Policy Envelope
# =============================================================================

class PolicyEnvelope(Base):
    """
    S&OP Policy Parameters (Policy Envelope)

    Contains the tunable parameters that govern downstream agents.
    Can be generated by Autonomy S&OP simulation (FULL mode) or
    provided by customer from their existing S&OP process (INPUT mode).

    Feed-forward contract to Supply + Allocation Agents.
    """
    __tablename__ = "planning_policy_envelope"

    id = Column(Integer, primary_key=True, index=True)
    hash = Column(String(64), unique=True, index=True, nullable=False)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)

    # Source tracking
    generated_by = Column(Enum(PolicySource, name="policy_source"), nullable=False, default=PolicySource.CUSTOMER_INPUT)

    # Safety Stock Targets (weeks of supply by category)
    # Format: {"frozen": 2.5, "refrigerated": 2.0, "dry": 3.0}
    safety_stock_targets = Column(JSON, nullable=False)

    # OTIF Floors by Segment
    # Format: {"strategic": 0.99, "standard": 0.95, "transactional": 0.90}
    otif_floors = Column(JSON, nullable=False)

    # Allocation Reserves (% reserved for priority segments)
    # Format: {"strategic": 0.30, "standard": 0.25}
    allocation_reserves = Column(JSON, nullable=False)

    # Expedite Budget Caps by Category
    # Format: {"frozen": 10000, "refrigerated": 8000, "dry": 5000}
    expedite_caps = Column(JSON, nullable=False)

    # DOS Ceilings (max days of supply)
    # Format: {"frozen": 14, "refrigerated": 10, "dry": 21}
    dos_ceilings = Column(JSON, nullable=True)

    # Supplier Concentration Limits
    # Format: {"Tyson": 0.40, "Hormel": 0.30, ...}
    supplier_concentration_limits = Column(JSON, nullable=True)

    # Financial Guardrails
    total_inventory_cap = Column(Float, nullable=True)  # $ cap
    gmroi_target = Column(Float, nullable=True)

    # Simulation metadata (only in FULL mode)
    simulation_run_id = Column(Integer, nullable=True)
    what_if_scenarios = Column(JSON, nullable=True)
    confidence_intervals = Column(JSON, nullable=True)

    # Period
    effective_date = Column(Date, nullable=False)
    expires_date = Column(Date, nullable=True)

    # Audit
    created_at = Column(DateTime, default=datetime.utcnow)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    approved_at = Column(DateTime, nullable=True)
    approved_by = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Relationships - use lazy="select" to defer class resolution
    config = relationship("SupplyChainConfig", lazy="select")
    customer = relationship("Customer", lazy="select")
    supply_baseline_packs = relationship("SupplyBaselinePack", back_populates="policy_envelope")

    __table_args__ = (
        Index("ix_policy_envelope_config_date", "config_id", "effective_date"),
    )

    def compute_hash(self) -> str:
        """Compute deterministic hash of policy parameters"""
        data = {
            "config_id": self.config_id,
            "safety_stock_targets": self.safety_stock_targets,
            "otif_floors": self.otif_floors,
            "allocation_reserves": self.allocation_reserves,
            "expedite_caps": self.expedite_caps,
            "effective_date": self.effective_date.isoformat() if self.effective_date else None,
        }
        json_str = json.dumps(data, sort_keys=True)
        return hashlib.sha256(json_str.encode()).hexdigest()[:64]


# =============================================================================
# Supply Baseline Pack (SupBP)
# =============================================================================

class SupplyBaselinePack(Base):
    """
    Supply Baseline Pack (SupBP)

    Non-authoritative mathematical grounding for Supply Agent.
    Contains candidate supply plans that the agent may accept, reject, or blend.

    In FULL mode: Multiple parameterized candidates from MRS/MRP engine.
    In INPUT mode: Single candidate from customer's existing MRP output.
    """
    __tablename__ = "supply_baseline_pack"

    id = Column(Integer, primary_key=True, index=True)
    hash = Column(String(64), unique=True, index=True, nullable=False)

    # Grounding link
    policy_envelope_id = Column(Integer, ForeignKey("planning_policy_envelope.id"), nullable=False, index=True)
    policy_envelope_hash = Column(String(64), nullable=False)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)

    # Source tracking
    generated_by = Column(Enum(PolicySource, name="policy_source"), nullable=False)

    # Candidates
    # Format: [
    #   {
    #     "method": "REORDER_POINT_V1",
    #     "orders": [{"sku": "FRZ-001", "supplier": "Tyson", "qty": 500, "date": "2026-02-10"}, ...],
    #     "projected_inventory": {"FRZ-001": [100, 150, 200, ...], ...},
    #     "projected_cost": 125000,
    #     "projected_otif": 0.96,
    #     "projected_dos": 12.5,
    #     "policy_params": {"safety_factor": 1.5, ...}
    #   },
    #   ...
    # ]
    candidates = Column(JSON, nullable=False)

    # Tradeoff frontier (only in FULL mode with multiple candidates)
    # Format: [{"method": "X", "cost": 100000, "otif": 0.94}, ...]
    tradeoff_frontier = Column(JSON, nullable=True)

    # Demand grounding (from UCF)
    demand_grounding_hash = Column(String(64), nullable=True)
    demand_by_sku = Column(JSON, nullable=True)  # Demand signal per SKU

    # Supply-side constraints snapshot
    supplier_capacities = Column(JSON, nullable=True)
    lead_times = Column(JSON, nullable=True)

    # Period
    planning_horizon_days = Column(Integer, default=28)
    generated_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    policy_envelope = relationship("PolicyEnvelope", back_populates="supply_baseline_packs")
    config = relationship("SupplyChainConfig")
    supply_commits = relationship("SupplyCommit", back_populates="supply_baseline_pack")

    def compute_hash(self) -> str:
        """Compute deterministic hash"""
        data = {
            "policy_envelope_hash": self.policy_envelope_hash,
            "candidates": self.candidates,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
        }
        json_str = json.dumps(data, sort_keys=True)
        return hashlib.sha256(json_str.encode()).hexdigest()[:64]


# =============================================================================
# Supply Commit (SC)
# =============================================================================

class SupplyCommit(Base):
    """
    Supply Commit (SC) - Agent-Owned Decision

    The best demand-informed, constraint-respecting set of supply actions
    (POs, transfer orders) that balances inventory investment against service risk
    within the S&OP policy envelope.

    Decision artifact contains:
    - order_qty[item, source, destination, time_bucket]
    - target_inventory_position
    - projected_otif[item, segment, bucket]
    - projected_inventory_cost
    - supply_pegging[demand → supply action]
    """
    __tablename__ = "supply_commit"

    id = Column(Integer, primary_key=True, index=True)
    hash = Column(String(64), unique=True, index=True, nullable=False)

    # Grounding link
    supply_baseline_pack_id = Column(Integer, ForeignKey("supply_baseline_pack.id"), nullable=False, index=True)
    supply_baseline_pack_hash = Column(String(64), nullable=False)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)

    # Selected candidate info
    selected_method = Column(String(50), nullable=True)  # Which SupBP candidate was selected/blended

    # Decision artifact
    # Format: [
    #   {
    #     "sku": "FRZ-001",
    #     "supplier_id": "Tyson",
    #     "destination_id": "DC-001",
    #     "order_qty": 500,
    #     "order_date": "2026-02-06",
    #     "expected_receipt_date": "2026-02-10",
    #     "confidence": 0.92,
    #     "rationale": "Inventory position below ROP"
    #   },
    #   ...
    # ]
    recommendations = Column(JSON, nullable=False)

    # Projected outcomes
    projected_inventory = Column(JSON, nullable=True)  # {sku: [day1, day2, ...]}
    projected_otif = Column(Float, nullable=True)
    projected_inventory_cost = Column(Float, nullable=True)
    projected_dos = Column(Float, nullable=True)

    # Supply pegging (demand → supply action)
    supply_pegging = Column(JSON, nullable=True)

    # Integrity violations (block submission)
    integrity_violations = Column(JSON, nullable=True)
    # Format: [{"type": "negative_inventory", "sku": "X", "period": 3, "detail": "..."}]

    # Risk flags (mark suggested)
    risk_flags = Column(JSON, nullable=True)
    # Format: [{"type": "service_risk", "sku": "X", "detail": "OTIF 88% vs 95% floor"}]

    # Status and workflow
    status = Column(Enum(CommitStatus, name="commit_status"), default=CommitStatus.PROPOSED, nullable=False, index=True)
    requires_review = Column(Boolean, default=False)
    review_reason = Column(Text, nullable=True)

    # Agent metadata
    agent_confidence = Column(Float, nullable=True)
    agent_reasoning = Column(Text, nullable=True)

    # Human interaction
    reviewed_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    override_details = Column(JSON, nullable=True)  # What was changed

    # Approval
    approved_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    approved_at = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    submitted_at = Column(DateTime, nullable=True)

    # Relationships
    supply_baseline_pack = relationship("SupplyBaselinePack", back_populates="supply_commits")
    config = relationship("SupplyChainConfig")
    allocation_commits = relationship("AllocationCommit", back_populates="supply_commit")

    __table_args__ = (
        Index("ix_supply_commit_status_created", "status", "created_at"),
        Index("ix_supply_commit_config_date", "config_id", "created_at"),
    )

    def compute_hash(self) -> str:
        """Compute deterministic hash"""
        data = {
            "supbp_hash": self.supply_baseline_pack_hash,
            "recommendations": self.recommendations,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
        json_str = json.dumps(data, sort_keys=True)
        return hashlib.sha256(json_str.encode()).hexdigest()[:64]


# =============================================================================
# Solver Baseline Pack (SBP)
# =============================================================================

class SolverBaselinePack(Base):
    """
    Solver Baseline Pack (SBP)

    Non-authoritative allocation candidates for Allocation Agent.
    Contains candidate allocations (fair-share, priority heuristic, LP, MILP).
    """
    __tablename__ = "solver_baseline_pack"

    id = Column(Integer, primary_key=True, index=True)
    hash = Column(String(64), unique=True, index=True, nullable=False)

    # Grounding link
    supply_commit_id = Column(Integer, ForeignKey("supply_commit.id"), nullable=False, index=True)
    supply_commit_hash = Column(String(64), nullable=False)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)

    # Candidates
    # Format: [
    #   {
    #     "method": "FAIR_SHARE_V1",
    #     "allocations": [{"sku": "X", "segment": "strategic", "qty": 100, "priority": 1}, ...],
    #     "unallocated": [...],
    #     "fair_share_deviation": 0.05,
    #     "service_floor_compliance": 0.98
    #   },
    #   ...
    # ]
    candidates = Column(JSON, nullable=False)

    # Constraint diagnostics
    binding_constraints = Column(JSON, nullable=True)
    slack_values = Column(JSON, nullable=True)
    gating_factors = Column(JSON, nullable=True)

    # Marginal value signals (Powell VFA outputs)
    marginal_values = Column(JSON, nullable=True)
    # Format: {"supply_shadow_price": {...}, "marginal_short_penalty": {...}}

    # Period
    generated_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    supply_commit = relationship("SupplyCommit")
    config = relationship("SupplyChainConfig")
    allocation_commits = relationship("AllocationCommit", back_populates="solver_baseline_pack")

    def compute_hash(self) -> str:
        """Compute deterministic hash"""
        data = {
            "supply_commit_hash": self.supply_commit_hash,
            "candidates": self.candidates,
        }
        json_str = json.dumps(data, sort_keys=True)
        return hashlib.sha256(json_str.encode()).hexdigest()[:64]


# =============================================================================
# Allocation Commit (AC)
# =============================================================================

class AllocationCommit(Base):
    """
    Allocation Commit (AC) - Agent-Owned Decision

    The best constraint-respecting distribution of constrained supply
    across demand segments and time buckets.

    Decision artifact contains:
    - entitlement_qty[item, segment, time_bucket]
    - allocation_priority
    - unallocated_qty
    - pegging_summary[supply_pool → segment attribution + gating factors]
    """
    __tablename__ = "allocation_commit"

    id = Column(Integer, primary_key=True, index=True)
    hash = Column(String(64), unique=True, index=True, nullable=False)

    # Grounding links
    supply_commit_id = Column(Integer, ForeignKey("supply_commit.id"), nullable=False, index=True)
    supply_commit_hash = Column(String(64), nullable=False)
    solver_baseline_pack_id = Column(Integer, ForeignKey("solver_baseline_pack.id"), nullable=False, index=True)
    solver_baseline_pack_hash = Column(String(64), nullable=False)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)

    # Selected method
    selected_method = Column(String(50), nullable=True)

    # Decision artifact
    # Format: [
    #   {
    #     "sku": "FRZ-001",
    #     "segment": "strategic",
    #     "customer_id": "CUST-001",
    #     "entitlement_qty": 200,
    #     "priority": 1,
    #     "time_bucket": "2026-W06"
    #   },
    #   ...
    # ]
    allocations = Column(JSON, nullable=False)

    # Unallocated quantities
    unallocated = Column(JSON, nullable=True)

    # Pegging summary
    pegging_summary = Column(JSON, nullable=True)

    # Integrity violations
    integrity_violations = Column(JSON, nullable=True)
    # Format: [{"type": "supply_conservation", "detail": "..."}]

    # Risk flags
    risk_flags = Column(JSON, nullable=True)
    # Format: [{"type": "fair_share_deviation", "segment": "X", "deviation": 0.15}]

    # Status
    status = Column(Enum(CommitStatus, name="commit_status"), default=CommitStatus.PROPOSED, nullable=False)
    requires_review = Column(Boolean, default=False)
    review_reason = Column(Text, nullable=True)

    # Agent metadata
    agent_confidence = Column(Float, nullable=True)
    agent_reasoning = Column(Text, nullable=True)

    # Human interaction
    reviewed_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    override_details = Column(JSON, nullable=True)

    # Approval
    approved_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    approved_at = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    submitted_at = Column(DateTime, nullable=True)

    # Relationships
    supply_commit = relationship("SupplyCommit", back_populates="allocation_commits")
    solver_baseline_pack = relationship("SolverBaselinePack", back_populates="allocation_commits")
    config = relationship("SupplyChainConfig")

    __table_args__ = (
        Index("ix_allocation_commit_status", "status", "created_at"),
    )

    def compute_hash(self) -> str:
        """Compute deterministic hash"""
        data = {
            "supply_commit_hash": self.supply_commit_hash,
            "sbp_hash": self.solver_baseline_pack_hash,
            "allocations": self.allocations,
        }
        json_str = json.dumps(data, sort_keys=True)
        return hashlib.sha256(json_str.encode()).hexdigest()[:64]


# =============================================================================
# Feed-Back Signal Tracking
# =============================================================================

class FeedBackSignal(Base):
    """
    Feed-Back Signals from Execution

    Outcome signals that re-tune upstream policy parameters.
    Enables the learning loop: outcome → parameter adjustment.
    """
    __tablename__ = "planning_feedback_signal"

    id = Column(Integer, primary_key=True, index=True)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)

    # Signal type
    signal_type = Column(String(50), nullable=False, index=True)
    # Types: actual_otif, allocation_shortfall, execution_adherence,
    #        expedite_frequency, eo_writeoff, override_outcome

    # Where measured
    measured_at_layer = Column(String(50), nullable=False)  # execution, allocation, supply, sop

    # What it re-tunes
    fed_back_to = Column(String(50), nullable=False)  # supply_agent, sop, allocation_agent

    # Signal value
    metric_name = Column(String(100), nullable=False)
    metric_value = Column(Float, nullable=False)
    threshold = Column(Float, nullable=True)
    deviation = Column(Float, nullable=True)

    # Detailed breakdown
    details = Column(JSON, nullable=True)
    # e.g., {"segment": "strategic", "sku": "FRZ-001", "actual_otif": 0.88, "floor": 0.99}

    # What parameter should be re-tuned
    suggested_retune = Column(JSON, nullable=True)
    # e.g., {"parameter": "safety_stock_targets.frozen", "current": 2.5, "suggested": 3.0}

    # Linked commits
    supply_commit_id = Column(Integer, ForeignKey("supply_commit.id"), nullable=True)
    allocation_commit_id = Column(Integer, ForeignKey("allocation_commit.id"), nullable=True)

    # Status
    acknowledged = Column(Boolean, default=False)
    actioned = Column(Boolean, default=False)
    actioned_at = Column(DateTime, nullable=True)
    actioned_by = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Timestamps
    measured_at = Column(DateTime, default=datetime.utcnow, index=True)

    __table_args__ = (
        Index("ix_feedback_signal_type_time", "signal_type", "measured_at"),
    )


# =============================================================================
# Agent Decision Metrics
# =============================================================================

class AgentDecisionMetrics(Base):
    """
    Metrics for agent decisions (both Supply and Allocation agents)

    Key metrics from the memo:
    - Touchless Rate: % of decisions not reviewed
    - Agent Score: Outcome lift from agent decisions vs baseline
    - User Score: Outcome lift from human overrides vs agent baseline
    - Human Override Rate: Decisions reviewed ÷ total in scope
    - Override Dependency: Repeated intervention on same decision identity
    - Downstream Coherence: SC vs what Allocation receives; AC vs what execution fulfills
    """
    __tablename__ = "agent_decision_metrics"

    id = Column(Integer, primary_key=True, index=True)

    # Context
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id"), nullable=False, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    agent_type = Column(String(50), nullable=False, index=True)  # supply_agent, allocation_agent

    # Period
    period_start = Column(Date, nullable=False)
    period_end = Column(Date, nullable=False)

    # Core metrics
    touchless_rate = Column(Float, nullable=True)  # % not reviewed
    agent_score = Column(Float, nullable=True)  # Outcome lift vs baseline
    user_score = Column(Float, nullable=True)  # Override lift vs agent
    human_override_rate = Column(Float, nullable=True)  # reviewed / total
    override_dependency_ratio = Column(Float, nullable=True)  # Repeated interventions
    downstream_coherence = Column(Float, nullable=True)  # SC→AC or AC→execution match

    # Volume metrics
    total_decisions = Column(Integer, nullable=True)
    auto_submitted = Column(Integer, nullable=True)
    reviewed = Column(Integer, nullable=True)
    overridden = Column(Integer, nullable=True)
    rejected = Column(Integer, nullable=True)

    # Integrity and risk
    integrity_violations_count = Column(Integer, nullable=True)
    risk_flags_count = Column(Integer, nullable=True)

    # Breakdown by category
    metrics_by_category = Column(JSON, nullable=True)
    # e.g., {"frozen": {...}, "refrigerated": {...}}

    # Timestamps
    computed_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_agent_metrics_period", "config_id", "agent_type", "period_start"),
    )


# =============================================================================
# Layer License (Modular Selling)
# =============================================================================

class LayerLicense(Base):
    """
    Tracks which cascade layers a group has purchased.

    Enables modular selling: customers buy only the layers they need.
    Layers not purchased show INPUT screens for manual parameter entry.

    Package tiers (bottom-up, each includes all below):
    - Foundation: execution only (deterministic engines)
    - AI Execution: execution + supply_agent + allocation_agent (TRM agents)
    - Planning: + mrs (MRS candidate generation)
    - Enterprise: + sop (S&OP simulation, full closed-loop)
    """
    __tablename__ = "layer_license"

    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    layer = Column(Enum(LayerName, name="layer_name"), nullable=False)
    mode = Column(Enum(LayerMode, name="layer_mode"), nullable=False, default=LayerMode.INPUT)

    # License metadata
    activated_at = Column(DateTime, nullable=True)
    expires_at = Column(DateTime, nullable=True)
    package_tier = Column(String(50), nullable=True)  # foundation, ai_execution, planning, enterprise

    # Audit
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    updated_by = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Relationships
    customer = relationship("Customer", lazy="select")

    __table_args__ = (
        Index("ix_layer_license_customer_layer", "customer_id", "layer", unique=True),
    )
