"""
Powell Allocation ORM Model

Maps to the powell_allocations table created by migration
20260202_powell_allocation_tables.py.

Stores priority x product x location allocations generated by the
Execution tGNN (or manually overridden by the allocmgr).
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, Text,
    ForeignKey, Index, UniqueConstraint,
)
from sqlalchemy.sql import func

from .base import Base


class PowellAllocation(Base):
    __tablename__ = "powell_allocations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id", ondelete="CASCADE"), nullable=False)
    product_id = Column(String(100), nullable=False)
    location_id = Column(String(100), nullable=False)
    priority = Column(Integer, nullable=False)  # 1=highest, 5=lowest

    # Quantities
    allocated_qty = Column(Float, nullable=False, server_default="0")
    consumed_qty = Column(Float, nullable=False, server_default="0")
    reserved_qty = Column(Float, nullable=False, server_default="0")

    # Source
    allocation_source = Column(String(50), nullable=True)  # 'tgnn', 'manual', 'rule'
    allocation_cadence = Column(String(20), nullable=False, server_default="weekly")  # 'daily', 'weekly'

    # tGNN reasoning — English explanation of why the tGNN generated this allocation
    decision_reasoning = Column(Text, nullable=True)

    # Validity
    valid_from = Column(DateTime, nullable=False)
    valid_to = Column(DateTime, nullable=False)
    is_active = Column(Boolean, nullable=False, server_default="true")

    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=False, server_default=func.now(), onupdate=func.now())

    __table_args__ = (
        Index("idx_alloc_config_product_loc", "config_id", "product_id", "location_id"),
        Index("idx_alloc_priority", "priority"),
        Index("idx_alloc_active", "is_active"),
        Index("idx_alloc_validity", "valid_from", "valid_to"),
        UniqueConstraint("config_id", "product_id", "location_id", "priority", "valid_from",
                         name="uq_powell_alloc_key"),
    )
