"""
Transportation Planning Models

Planning-specific entities for transportation management:
- ShippingForecast: Predicted freight volumes by lane/mode/period
- CapacityTarget: Required carrier capacity by lane/mode
- TransportationPlan: The Plan of Record — load builds, carrier assignments
- TransportationPlanItem: Individual planned load within a transportation plan

These mirror the SC planning cascade (Demand → Supply → MPS → Execution)
adapted for transportation:
  ShippingForecast → CapacityTarget → TransportationPlan → Execution (TRM)

Plan versions follow the same strict separation as SC Planning:
- 'live': Plan of Record — what the business operates on (agent-generated)
- 'tms_baseline': Current TMS/ERP plan — comparison baseline
- 'decision_action': User overrides from Decision Stream
"""

from sqlalchemy import (
    Column,
    Integer,
    String,
    Double,
    Boolean,
    ForeignKey,
    DateTime,
    Date,
    JSON,
    Text,
    Index,
    UniqueConstraint,
    Enum as SAEnum,
    text,
)
from sqlalchemy.orm import relationship
from datetime import datetime
from enum import Enum as PyEnum
from .base import Base


# ============================================================================
# Enums
# ============================================================================

class ForecastMethod(str, PyEnum):
    """How the shipping forecast was generated"""
    STATISTICAL = "STATISTICAL"       # Time series model
    ML = "ML"                         # Machine learning (tGNN, LightGBM)
    CONSENSUS = "CONSENSUS"           # Manual/collaborative
    EXTERNAL = "EXTERNAL"             # From TMS/ERP system
    CONFORMAL = "CONFORMAL"           # Conformal prediction (P10/P50/P90)


# PlanStatus + PlanItemStatus moved to Core 2026-05-02 per §3.39
# (canonical-state enum vocabulary parallels supply_plan).
# See Autonomy-Core docs/MIGRATION_REGISTER.md §3.39 for the rationale.
from azirella_data_model.transport_plan import PlanItemStatus, PlanStatus  # noqa: F401

from azirella_data_model.optimization.plan_versions import PlanVersion, is_constrained_for_version  # noqa: E402


# Today's system is NOT constrained-planning. Agent-written plans are
# decision records labelled `constrained_live` for UI continuity. Flip
# to True when the Integrated Balancer lands (Phase 3).
PLANNING_IS_CONSTRAINED = False


# ============================================================================
# Shipping Forecast (Demand Side)
# ============================================================================

class ShippingForecast(Base):
    """
    Predicted freight volume by lane, mode, and time period
    TMS Entity: shipping_forecast
    Maps to Forecast/DemandPlan in SC context

    Generated by LoadVolumeSensingTRM or imported from external systems.
    Feeds into CapacityTarget calculation.
    """
    __tablename__ = "shipping_forecast"

    id = Column(Integer, primary_key=True, autoincrement=True)
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id", ondelete="CASCADE"), nullable=False)
    plan_version = Column(String(20), nullable=False, default="live",
                          comment="live, tms_baseline, decision_action")

    # Dimensions
    lane_id = Column(Integer, ForeignKey("transportation_lane.id"))
    origin_site_id = Column(Integer, ForeignKey("site.id"))
    destination_site_id = Column(Integer, ForeignKey("site.id"))
    mode = Column(String(20), comment="FTL, LTL, INTERMODAL, OCEAN, AIR")
    commodity_id = Column(Integer, ForeignKey("commodity.id"))

    # Time period
    forecast_date = Column(Date, nullable=False, comment="Start of the forecast period")
    period_type = Column(String(10), default="WEEK", comment="DAY, WEEK, MONTH")

    # Volume forecast
    forecast_loads = Column(Double, comment="Predicted number of loads")
    forecast_weight = Column(Double, comment="Predicted total weight")
    forecast_volume = Column(Double, comment="Predicted total volume (cuft)")
    forecast_pallets = Column(Double, comment="Predicted total pallets")

    # Conformal prediction bounds
    forecast_loads_p10 = Column(Double, comment="10th percentile — low scenario")
    forecast_loads_p50 = Column(Double, comment="50th percentile — most likely")
    forecast_loads_p90 = Column(Double, comment="90th percentile — high scenario")

    # Method and quality
    forecast_method = Column(SAEnum(ForecastMethod, name="forecast_method_enum"))
    model_id = Column(String(100), comment="ML model version that generated this")
    mape = Column(Double, comment="Mean Absolute Percentage Error for this forecast")
    confidence_score = Column(Double, comment="0-1 model confidence")

    # Adjustments
    manual_adjustment = Column(Double, default=0, comment="User override delta (loads)")
    adjustment_reason = Column(String(500))
    adjusted_by_user_id = Column(Integer, ForeignKey("users.id"))

    # Source
    source = Column(String(100), comment="AGENT, TMS, ERP, MANUAL")

    tenant_id = Column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    config = relationship("SupplyChainConfig")
    lane = relationship("TransportationLane")
    origin = relationship("Site", foreign_keys=[origin_site_id])
    destination = relationship("Site", foreign_keys=[destination_site_id])
    commodity = relationship("Commodity")

    __table_args__ = (
        Index('idx_shipping_forecast_lookup', 'config_id', 'plan_version', 'forecast_date', 'lane_id'),
        Index('idx_forecast_tenant_period', 'tenant_id', 'forecast_date', 'period_type'),
        Index('idx_forecast_lane_mode', 'lane_id', 'mode', 'forecast_date'),
    )


# ============================================================================
# Capacity Target (Supply Side)
# ============================================================================

class CapacityTarget(Base):
    """
    Required carrier capacity by lane/mode/period
    TMS Entity: capacity_target
    Maps to InventoryTarget/SafetyStock in SC context

    Calculated from ShippingForecast + buffer policies.
    Feeds into TransportationPlan carrier assignment.
    """
    __tablename__ = "capacity_target"

    id = Column(Integer, primary_key=True, autoincrement=True)
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id", ondelete="CASCADE"), nullable=False)
    plan_version = Column(String(20), nullable=False, default="live")

    # Dimensions
    lane_id = Column(Integer, ForeignKey("transportation_lane.id"))
    origin_site_id = Column(Integer, ForeignKey("site.id"))
    destination_site_id = Column(Integer, ForeignKey("site.id"))
    mode = Column(String(20))
    carrier_id = Column(Integer, ForeignKey("carrier.id"))

    # Time period
    target_date = Column(Date, nullable=False)
    period_type = Column(String(10), default="WEEK")

    # Capacity requirements
    required_loads = Column(Double, nullable=False, comment="Loads needed for this period")
    committed_loads = Column(Double, default=0, comment="Loads committed by carriers")
    available_loads = Column(Double, default=0, comment="Carrier capacity available")
    gap_loads = Column(Double, default=0, comment="Unmet capacity (required - committed)")

    # Buffer (like safety stock for transport)
    buffer_loads = Column(Double, default=0, comment="Extra capacity buffer above forecast")
    buffer_policy = Column(String(20), comment="FIXED, PCT_FORECAST, CONFORMAL")
    buffer_pct = Column(Double, comment="Buffer as % of forecast")

    # Cost
    target_cost_per_load = Column(Double)
    target_total_cost = Column(Double)
    budget_limit = Column(Double)

    # Conformal bounds on capacity need
    required_loads_p10 = Column(Double)
    required_loads_p90 = Column(Double)

    tenant_id = Column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    config = relationship("SupplyChainConfig")
    lane = relationship("TransportationLane")
    origin = relationship("Site", foreign_keys=[origin_site_id])
    destination = relationship("Site", foreign_keys=[destination_site_id])
    carrier = relationship("Carrier")

    __table_args__ = (
        Index('idx_capacity_target_lookup', 'config_id', 'plan_version', 'target_date', 'lane_id'),
        Index('idx_capacity_target_gap', 'tenant_id', 'gap_loads'),
    )


