"""
Transportation Planning Models

Planning-specific entities for transportation management:
- ShippingForecast: Predicted freight volumes by lane/mode/period
- CapacityTarget: Required carrier capacity by lane/mode
- TransportationPlan: The Plan of Record — load builds, carrier assignments
- TransportationPlanItem: Individual planned load within a transportation plan

These mirror the SC planning cascade (Demand → Supply → MPS → Execution)
adapted for transportation:
  ShippingForecast → CapacityTarget → TransportationPlan → Execution (TRM)

Plan versions follow the same strict separation as SC Planning:
- 'live': Plan of Record — what the business operates on (agent-generated)
- 'tms_baseline': Current TMS/ERP plan — comparison baseline
- 'decision_action': User overrides from Decision Stream
"""

from sqlalchemy import (
    Column,
    Integer,
    String,
    Double,
    Boolean,
    ForeignKey,
    DateTime,
    Date,
    JSON,
    Text,
    Index,
    UniqueConstraint,
    Enum as SAEnum,
    text,
)
from sqlalchemy.orm import relationship
from datetime import datetime
from enum import Enum as PyEnum
from .base import Base


# ============================================================================
# Enums
# ============================================================================

class ForecastMethod(str, PyEnum):
    """How the shipping forecast was generated"""
    STATISTICAL = "STATISTICAL"       # Time series model
    ML = "ML"                         # Machine learning (tGNN, LightGBM)
    CONSENSUS = "CONSENSUS"           # Manual/collaborative
    EXTERNAL = "EXTERNAL"             # From TMS/ERP system
    CONFORMAL = "CONFORMAL"           # Conformal prediction (P10/P50/P90)


class PlanStatus(str, PyEnum):
    """Transportation plan lifecycle"""
    DRAFT = "DRAFT"
    OPTIMIZING = "OPTIMIZING"
    READY = "READY"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    SUPERSEDED = "SUPERSEDED"


from azirella_data_model.optimization.plan_versions import PlanVersion, is_constrained_for_version  # noqa: E402


# Today's system is NOT constrained-planning. Agent-written plans are
# decision records labelled `constrained_live` for UI continuity. Flip
# to True when the Integrated Balancer lands (Phase 3).
PLANNING_IS_CONSTRAINED = False


class PlanItemStatus(str, PyEnum):
    """Individual planned load status"""
    PLANNED = "PLANNED"
    CARRIER_ASSIGNED = "CARRIER_ASSIGNED"
    TENDERED = "TENDERED"
    CONFIRMED = "CONFIRMED"
    IN_EXECUTION = "IN_EXECUTION"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


# ============================================================================
# Shipping Forecast (Demand Side)
# ============================================================================

class ShippingForecast(Base):
    """
    Predicted freight volume by lane, mode, and time period
    TMS Entity: shipping_forecast
    Maps to Forecast/DemandPlan in SC context

    Generated by DemandSensingTRM or imported from external systems.
    Feeds into CapacityTarget calculation.
    """
    __tablename__ = "shipping_forecast"

    id = Column(Integer, primary_key=True, autoincrement=True)
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id", ondelete="CASCADE"), nullable=False)
    plan_version = Column(String(20), nullable=False, default="live",
                          comment="live, tms_baseline, decision_action")

    # Dimensions
    lane_id = Column(Integer, ForeignKey("transportation_lane.id"))
    origin_site_id = Column(Integer, ForeignKey("site.id"))
    destination_site_id = Column(Integer, ForeignKey("site.id"))
    mode = Column(String(20), comment="FTL, LTL, INTERMODAL, OCEAN, AIR")
    commodity_id = Column(Integer, ForeignKey("commodity.id"))

    # Time period
    forecast_date = Column(Date, nullable=False, comment="Start of the forecast period")
    period_type = Column(String(10), default="WEEK", comment="DAY, WEEK, MONTH")

    # Volume forecast
    forecast_loads = Column(Double, comment="Predicted number of loads")
    forecast_weight = Column(Double, comment="Predicted total weight")
    forecast_volume = Column(Double, comment="Predicted total volume (cuft)")
    forecast_pallets = Column(Double, comment="Predicted total pallets")

    # Conformal prediction bounds
    forecast_loads_p10 = Column(Double, comment="10th percentile — low scenario")
    forecast_loads_p50 = Column(Double, comment="50th percentile — most likely")
    forecast_loads_p90 = Column(Double, comment="90th percentile — high scenario")

    # Method and quality
    forecast_method = Column(SAEnum(ForecastMethod, name="forecast_method_enum"))
    model_id = Column(String(100), comment="ML model version that generated this")
    mape = Column(Double, comment="Mean Absolute Percentage Error for this forecast")
    confidence_score = Column(Double, comment="0-1 model confidence")

    # Adjustments
    manual_adjustment = Column(Double, default=0, comment="User override delta (loads)")
    adjustment_reason = Column(String(500))
    adjusted_by_user_id = Column(Integer, ForeignKey("users.id"))

    # Source
    source = Column(String(100), comment="AGENT, TMS, ERP, MANUAL")

    tenant_id = Column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    config = relationship("SupplyChainConfig")
    lane = relationship("TransportationLane")
    origin = relationship("Site", foreign_keys=[origin_site_id])
    destination = relationship("Site", foreign_keys=[destination_site_id])
    commodity = relationship("Commodity")

    __table_args__ = (
        Index('idx_shipping_forecast_lookup', 'config_id', 'plan_version', 'forecast_date', 'lane_id'),
        Index('idx_forecast_tenant_period', 'tenant_id', 'forecast_date', 'period_type'),
        Index('idx_forecast_lane_mode', 'lane_id', 'mode', 'forecast_date'),
    )


# ============================================================================
# Capacity Target (Supply Side)
# ============================================================================

class CapacityTarget(Base):
    """
    Required carrier capacity by lane/mode/period
    TMS Entity: capacity_target
    Maps to InventoryTarget/SafetyStock in SC context

    Calculated from ShippingForecast + buffer policies.
    Feeds into TransportationPlan carrier assignment.
    """
    __tablename__ = "capacity_target"

    id = Column(Integer, primary_key=True, autoincrement=True)
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id", ondelete="CASCADE"), nullable=False)
    plan_version = Column(String(20), nullable=False, default="live")

    # Dimensions
    lane_id = Column(Integer, ForeignKey("transportation_lane.id"))
    origin_site_id = Column(Integer, ForeignKey("site.id"))
    destination_site_id = Column(Integer, ForeignKey("site.id"))
    mode = Column(String(20))
    carrier_id = Column(Integer, ForeignKey("carrier.id"))

    # Time period
    target_date = Column(Date, nullable=False)
    period_type = Column(String(10), default="WEEK")

    # Capacity requirements
    required_loads = Column(Double, nullable=False, comment="Loads needed for this period")
    committed_loads = Column(Double, default=0, comment="Loads committed by carriers")
    available_loads = Column(Double, default=0, comment="Carrier capacity available")
    gap_loads = Column(Double, default=0, comment="Unmet capacity (required - committed)")

    # Buffer (like safety stock for transport)
    buffer_loads = Column(Double, default=0, comment="Extra capacity buffer above forecast")
    buffer_policy = Column(String(20), comment="FIXED, PCT_FORECAST, CONFORMAL")
    buffer_pct = Column(Double, comment="Buffer as % of forecast")

    # Cost
    target_cost_per_load = Column(Double)
    target_total_cost = Column(Double)
    budget_limit = Column(Double)

    # Conformal bounds on capacity need
    required_loads_p10 = Column(Double)
    required_loads_p90 = Column(Double)

    tenant_id = Column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    config = relationship("SupplyChainConfig")
    lane = relationship("TransportationLane")
    origin = relationship("Site", foreign_keys=[origin_site_id])
    destination = relationship("Site", foreign_keys=[destination_site_id])
    carrier = relationship("Carrier")

    __table_args__ = (
        Index('idx_capacity_target_lookup', 'config_id', 'plan_version', 'target_date', 'lane_id'),
        Index('idx_capacity_target_gap', 'tenant_id', 'gap_loads'),
    )


# ============================================================================
# Transportation Plan (Execution Plan — replaces MPS)
# ============================================================================

class TransportationPlan(Base):
    """
    Transportation Plan of Record — the master execution plan
    TMS Entity: transportation_plan
    Maps to MPS/SupplyPlan in SC context

    Generated daily by the planning cascade (S&OP → Capacity → LoadBuild → Assign).
    Contains planned loads with carrier assignments.
    """
    __tablename__ = "transportation_plan"

    id = Column(Integer, primary_key=True, autoincrement=True)
    config_id = Column(Integer, ForeignKey("supply_chain_configs.id", ondelete="CASCADE"), nullable=False)
    # `plan_version` is the honest label for what this row represents:
    #   unconstrained_reference — Demand Potential or Unconstrained Movement Plan
    #   constrained_live        — Constrained Committed Plan (today's agent-written plan;
    #                              until the Integrated Balancer ships, this is really a
    #                              decision record — see docs/TACTICAL_PLANNING_REARCHITECTURE.md)
    #   erp_baseline            — External TMS / ERP plan, for comparison
    #   decision_action         — User-authored override plan
    # Kept as String (not Enum) so the values can evolve without Alembic churn; the
    # canonical enum is `app.models.tms_planning.PlanVersion`.
    plan_version = Column(String(30), nullable=False, default="constrained_live")
    plan_name = Column(String(200))

    status = Column(SAEnum(PlanStatus, name="plan_status_enum"), nullable=False, default=PlanStatus.DRAFT)

    # Planning horizon
    plan_start_date = Column(Date, nullable=False)
    plan_end_date = Column(Date, nullable=False)
    planning_horizon_days = Column(Integer)

    # Summary metrics (aggregated from plan items)
    total_planned_loads = Column(Integer, default=0)
    total_planned_shipments = Column(Integer, default=0)
    total_estimated_cost = Column(Double, default=0)
    total_estimated_miles = Column(Double, default=0)
    avg_cost_per_mile = Column(Double)
    avg_utilization_pct = Column(Double, comment="Average load utilization %")
    carrier_count = Column(Integer, comment="Number of distinct carriers assigned")

    # Optimization metadata
    optimization_method = Column(String(50), comment="AGENT, MANUAL, HYBRID")
    optimization_score = Column(Double, comment="Overall plan quality 0-1")
    optimization_duration_sec = Column(Double, comment="Time to generate plan")
    optimization_metadata = Column(JSON)

    # Comparison to baseline
    cost_vs_baseline_pct = Column(Double, comment="% cost change vs tms_baseline")
    service_vs_baseline_pct = Column(Double, comment="% OTD change vs tms_baseline")

    # Approval
    approved_by_user_id = Column(Integer, ForeignKey("users.id"))
    approved_at = Column(DateTime)

    # Generation
    generated_by = Column(String(20), comment="AGENT, USER, SCHEDULED")
    cascade_run_id = Column(String(100), comment="Planning cascade execution ID")

    tenant_id = Column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    config = relationship("SupplyChainConfig")
    items = relationship("TransportationPlanItem", back_populates="plan", cascade="all, delete-orphan")

    __table_args__ = (
        Index('idx_transport_plan_lookup', 'config_id', 'plan_version', 'status'),
        Index('idx_transport_plan_dates', 'tenant_id', 'plan_start_date', 'plan_end_date'),
    )


class TransportationPlanItem(Base):
    """
    Individual planned load within a transportation plan
    TMS Entity: transportation_plan_item
    Maps to MPSPlanItem in SC context

    Each item represents a planned movement: shipments consolidated into a load,
    assigned to a carrier, with estimated cost and timing.
    """
    __tablename__ = "transportation_plan_item"

    id = Column(Integer, primary_key=True, autoincrement=True)
    plan_id = Column(Integer, ForeignKey("transportation_plan.id", ondelete="CASCADE"), nullable=False)

    # Route
    origin_site_id = Column(Integer, ForeignKey("site.id"), nullable=False)
    destination_site_id = Column(Integer, ForeignKey("site.id"), nullable=False)
    lane_id = Column(Integer, ForeignKey("transportation_lane.id"))
    mode = Column(String(20), nullable=False)
    equipment_type = Column(String(30))

    # Assignment
    carrier_id = Column(Integer, ForeignKey("carrier.id"))
    rate_id = Column(Integer, ForeignKey("freight_rate.id"))
    status = Column(SAEnum(PlanItemStatus, name="plan_item_status_enum"),
                    nullable=False, default=PlanItemStatus.PLANNED)

    # Timing
    planned_pickup_date = Column(DateTime, nullable=False)
    planned_delivery_date = Column(DateTime, nullable=False)

    # Volume
    shipment_count = Column(Integer, default=1)
    total_weight = Column(Double)
    total_volume = Column(Double)
    total_pallets = Column(Integer)
    utilization_pct = Column(Double)

    # Cost
    estimated_cost = Column(Double)
    estimated_cost_per_mile = Column(Double)
    distance_miles = Column(Double)

    # Multi-stop
    stops = Column(JSON, comment='[{"site_id": 1, "type": "PICKUP"}, {"site_id": 2, "type": "DELIVERY"}]')
    is_multi_stop = Column(Boolean, default=False)

    # Linked execution records (populated when plan executes)
    load_id = Column(Integer, ForeignKey("load.id"))
    shipment_ids = Column(JSON, comment="List of shipment IDs consolidated into this load")

    # Agent decision
    agent_decision_id = Column(String(100), comment="FK to powell_decisions")
    selection_rationale = Column(JSON, comment='{"carrier_score": 0.92, "cost_rank": 1, ...}')

    tenant_id = Column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    plan = relationship("TransportationPlan", back_populates="items")
    origin = relationship("Site", foreign_keys=[origin_site_id])
    destination = relationship("Site", foreign_keys=[destination_site_id])
    lane = relationship("TransportationLane")
    carrier = relationship("Carrier")
    rate = relationship("FreightRate")
    load = relationship("Load")

    __table_args__ = (
        Index('idx_plan_item_plan', 'plan_id', 'status'),
        Index('idx_plan_item_dates', 'planned_pickup_date', 'planned_delivery_date'),
        Index('idx_plan_item_carrier', 'carrier_id', 'status'),
        Index('idx_plan_item_lane', 'lane_id', 'mode'),
    )
