"""
Allocation Service for Priority-Based ATP

Manages priority allocations generated by tGNN at the execution level.
Allocations are at the granularity of: priority × product × site

Key concepts:
- Allocations are fixed for a planning period (configurable cadence, default weekly)
- tGNN generates allocations based on demand patterns and structural context
- TRM executes AATP using these allocations with specific consumption logic
- Feedback from actual consumption informs the next allocation cycle

Configuration:
- Allocation cadence: Group admin configurable, default weekly
- Unfulfillable orders: Partial fill (default), reject, or backlog
- OTIF measurement: Always on

References:
- Conversation with Claude on AATP architecture
- Powell (2022) Sequential Decision Analytics - CFA for allocation policy
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any
from enum import Enum
from datetime import datetime, date, timedelta
import logging

logger = logging.getLogger(__name__)


class AllocationCadence(Enum):
    """Frequency of allocation regeneration by tGNN"""
    DAILY = "daily"
    WEEKLY = "weekly"  # Default
    BIWEEKLY = "biweekly"
    MONTHLY = "monthly"


class UnfulfillableOrderAction(Enum):
    """Action when order cannot be fully fulfilled"""
    PARTIAL_FILL = "partial_fill"  # Default - fulfill what's available
    REJECT = "reject"  # Reject entire order
    BACKLOG = "backlog"  # Accept and backlog unfulfilled portion


@dataclass
class PriorityAllocation:
    """
    Allocation for a specific priority × product × site combination.

    Generated by tGNN on the configured cadence.
    """
    priority: int  # 1 = highest priority
    product_id: str
    site_id: str  # AWS SC DM canonical

    # Allocation quantities
    allocated_qty: float
    consumed_qty: float = 0.0

    # Period validity
    valid_from: date = field(default_factory=date.today)
    valid_to: Optional[date] = None

    # Source tracking
    demand_source: Optional[str] = None  # e.g., "key_account", "retail", "spot_market"
    generated_by: str = "tgnn"  # "tgnn", "manual", "default"

    @property
    def available_qty(self) -> float:
        """Remaining available quantity"""
        return max(0, self.allocated_qty - self.consumed_qty)

    @property
    def utilization(self) -> float:
        """Utilization percentage"""
        if self.allocated_qty == 0:
            return 0.0
        return self.consumed_qty / self.allocated_qty

    def consume(self, qty: float) -> float:
        """
        Consume from this allocation.

        Returns: Actually consumed quantity (may be less than requested)
        """
        available = self.available_qty
        actually_consumed = min(qty, available)
        self.consumed_qty += actually_consumed
        return actually_consumed

    def to_dict(self) -> Dict[str, Any]:
        return {
            "priority": self.priority,
            "product_id": self.product_id,
            "site_id": self.site_id,
            "allocated_qty": self.allocated_qty,
            "consumed_qty": self.consumed_qty,
            "available_qty": self.available_qty,
            "utilization": self.utilization,
            "valid_from": self.valid_from.isoformat() if self.valid_from else None,
            "valid_to": self.valid_to.isoformat() if self.valid_to else None,
            "demand_source": self.demand_source,
            "generated_by": self.generated_by,
        }


@dataclass
class AllocationConfig:
    """
    Configuration for allocation service.

    Group admin can modify these settings.
    """
    cadence: AllocationCadence = AllocationCadence.WEEKLY
    unfulfillable_action: UnfulfillableOrderAction = UnfulfillableOrderAction.PARTIAL_FILL
    measure_otif: bool = True

    # Priority configuration
    num_priorities: int = 5  # P1 through P5
    default_priority_by_source: Dict[str, int] = field(default_factory=dict)

    # Allocation defaults
    default_allocation_pct: Dict[int, float] = field(default_factory=dict)  # priority -> % of forecast

    def __post_init__(self):
        # Set defaults if not provided
        if not self.default_priority_by_source:
            self.default_priority_by_source = {
                "key_account": 1,
                "contract": 2,
                "retail": 3,
                "wholesale": 4,
                "spot_market": 5,
            }

        if not self.default_allocation_pct:
            # Default allocation percentages by priority
            self.default_allocation_pct = {
                1: 0.30,  # 30% for P1
                2: 0.25,  # 25% for P2
                3: 0.20,  # 20% for P3
                4: 0.15,  # 15% for P4
                5: 0.10,  # 10% for P5
            }


@dataclass
class ConsumptionResult:
    """Result of attempting to consume from allocations"""
    order_id: str
    order_priority: int
    requested_qty: float
    fulfilled_qty: float

    # Consumption breakdown by priority tier
    consumption_by_priority: Dict[int, float] = field(default_factory=dict)

    # Status
    fully_fulfilled: bool = False
    action_taken: UnfulfillableOrderAction = UnfulfillableOrderAction.PARTIAL_FILL

    # OTIF tracking
    on_time: bool = True
    in_full: bool = False

    @property
    def fill_rate(self) -> float:
        if self.requested_qty == 0:
            return 1.0
        return self.fulfilled_qty / self.requested_qty

    @property
    def shortfall(self) -> float:
        return max(0, self.requested_qty - self.fulfilled_qty)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "order_id": self.order_id,
            "order_priority": self.order_priority,
            "requested_qty": self.requested_qty,
            "fulfilled_qty": self.fulfilled_qty,
            "fill_rate": self.fill_rate,
            "shortfall": self.shortfall,
            "consumption_by_priority": self.consumption_by_priority,
            "fully_fulfilled": self.fully_fulfilled,
            "action_taken": self.action_taken.value,
            "on_time": self.on_time,
            "in_full": self.in_full,
        }


class AllocationService:
    """
    Manages priority-based allocations for AATP.

    Allocations are generated by tGNN on a configurable cadence
    and consumed by TRM-based ATP executor.

    Key responsibilities:
    1. Store and manage allocations (priority × product × site)
    2. Execute consumption logic per the defined rules
    3. Track consumption for feedback to next tGNN cycle
    4. Measure OTIF metrics
    """

    def __init__(self, config: Optional[AllocationConfig] = None):
        """
        Initialize allocation service.

        Args:
            config: Allocation configuration (uses defaults if not provided)
        """
        self.config = config or AllocationConfig()

        # Allocations indexed by (product_id, location_id)
        # Each entry is a dict of priority -> PriorityAllocation
        self._allocations: Dict[Tuple[str, str], Dict[int, PriorityAllocation]] = {}

        # Consumption history for feedback
        self._consumption_history: List[ConsumptionResult] = []

        # Current allocation period
        self._period_start: Optional[date] = None
        self._period_end: Optional[date] = None

    def set_allocations(
        self,
        allocations: List[PriorityAllocation],
        period_start: Optional[date] = None,
        period_end: Optional[date] = None
    ):
        """
        Set allocations for a planning period.

        Called by tGNN when generating new allocations.

        Args:
            allocations: List of allocations from tGNN
            period_start: Start of allocation period
            period_end: End of allocation period
        """
        self._allocations.clear()

        for alloc in allocations:
            key = (alloc.product_id, alloc.site_id)
            if key not in self._allocations:
                self._allocations[key] = {}
            self._allocations[key][alloc.priority] = alloc

        # Set period
        # TODO(virtual-clock): AllocationService has no tenant/config context; thread
        # tenant_id through AllocationConfig or set_allocations to use tenant_today_sync.
        self._period_start = period_start or date.today()
        if period_end:
            self._period_end = period_end
        else:
            # Calculate based on cadence
            if self.config.cadence == AllocationCadence.DAILY:
                self._period_end = self._period_start + timedelta(days=1)
            elif self.config.cadence == AllocationCadence.WEEKLY:
                self._period_end = self._period_start + timedelta(weeks=1)
            elif self.config.cadence == AllocationCadence.BIWEEKLY:
                self._period_end = self._period_start + timedelta(weeks=2)
            else:  # Monthly
                self._period_end = self._period_start + timedelta(days=30)

        logger.info(
            f"Set {len(allocations)} allocations for period "
            f"{self._period_start} to {self._period_end}"
        )

    def generate_default_allocations(
        self,
        product_id: str,
        location_id: str,
        total_available: float,
        demand_sources: Optional[Dict[str, float]] = None
    ) -> List[PriorityAllocation]:
        """
        Generate default allocations when tGNN hasn't run yet.

        Uses default allocation percentages by priority.

        Args:
            product_id: Product ID
            location_id: Site ID
            total_available: Total available inventory/capacity
            demand_sources: Optional demand by source for smarter defaults

        Returns:
            List of PriorityAllocation objects
        """
        allocations = []

        for priority in range(1, self.config.num_priorities + 1):
            pct = self.config.default_allocation_pct.get(priority, 0.1)
            allocated = total_available * pct

            allocations.append(PriorityAllocation(
                priority=priority,
                product_id=product_id,
                site_id=location_id,  # method param name stays; field is site_id
                allocated_qty=allocated,
                generated_by="default",
            ))

        return allocations

    def consume_for_order(
        self,
        order_id: str,
        product_id: str,
        location_id: str,
        requested_qty: float,
        order_priority: int,
        demand_source: Optional[str] = None,
        requested_date: Optional[date] = None
    ) -> ConsumptionResult:
        """
        Attempt to consume from allocations for an order.

        Consumption logic (from conversation):
        1. First try own tier (e.g., P3 for a P3 order)
        2. If exhausted, go to the bottom (e.g., P5)
        3. Work upward: P4, then back to check if more became available
        4. Stop at own tier (already tried)
        5. Cannot consume from tiers higher than own

        Args:
            order_id: Unique order identifier
            product_id: Product being ordered
            location_id: Site for fulfillment
            requested_qty: Quantity requested
            order_priority: Priority of the order (1 = highest)
            demand_source: Source of demand (for priority lookup if not specified)
            requested_date: Requested delivery date (for OTIF)

        Returns:
            ConsumptionResult with fulfillment details
        """
        # Determine priority if not specified
        if order_priority is None and demand_source:
            order_priority = self.config.default_priority_by_source.get(
                demand_source, self.config.num_priorities
            )

        result = ConsumptionResult(
            order_id=order_id,
            order_priority=order_priority,
            requested_qty=requested_qty,
            fulfilled_qty=0.0,
        )

        key = (product_id, location_id)
        if key not in self._allocations:
            logger.warning(f"No allocations found for {product_id} at {location_id}")
            result.action_taken = self.config.unfulfillable_action
            self._consumption_history.append(result)
            return result

        allocations = self._allocations[key]
        remaining_need = requested_qty

        # Build consumption sequence per the defined logic:
        # 1. Own tier first
        # 2. Bottom tier (highest number)
        # 3. Work upward to own tier
        consumption_sequence = self._build_consumption_sequence(
            order_priority, self.config.num_priorities
        )

        for priority in consumption_sequence:
            if remaining_need <= 0:
                break

            if priority not in allocations:
                continue

            alloc = allocations[priority]
            consumed = alloc.consume(remaining_need)

            if consumed > 0:
                result.consumption_by_priority[priority] = consumed
                result.fulfilled_qty += consumed
                remaining_need -= consumed

        # Determine final status
        result.fully_fulfilled = remaining_need <= 0
        result.in_full = result.fully_fulfilled

        # OTIF tracking
        if requested_date:
            # TODO(virtual-clock): AllocationService has no tenant/config context;
            # thread tenant_id through to use tenant_today_sync for OTIF comparison.
            result.on_time = date.today() <= requested_date

        # Handle unfulfillable portion
        if not result.fully_fulfilled:
            result.action_taken = self.config.unfulfillable_action
            if self.config.unfulfillable_action == UnfulfillableOrderAction.REJECT:
                # Rollback consumption
                for priority, qty in result.consumption_by_priority.items():
                    allocations[priority].consumed_qty -= qty
                result.fulfilled_qty = 0.0
                result.consumption_by_priority.clear()

        # Record for feedback
        self._consumption_history.append(result)

        return result

    def _build_consumption_sequence(
        self,
        order_priority: int,
        num_priorities: int
    ) -> List[int]:
        """
        Build the consumption sequence for an order.

        Logic:
        1. Own tier first
        2. Lowest tier (highest number)
        3. Work upward toward own tier
        4. Cannot go above own tier

        Example for P2 order with 5 priorities:
        Sequence: [2, 5, 4, 3]

        Example for P4 order with 5 priorities:
        Sequence: [4, 5]
        """
        sequence = [order_priority]  # Own tier first

        # Then from bottom up, stopping at own tier
        for p in range(num_priorities, order_priority, -1):
            if p != order_priority:
                sequence.append(p)

        return sequence

    def get_allocation_status(
        self,
        product_id: str,
        location_id: str
    ) -> Dict[int, Dict[str, float]]:
        """
        Get current allocation status for a product/site.

        Returns dict of priority -> {allocated, consumed, available, utilization}
        """
        key = (product_id, location_id)
        if key not in self._allocations:
            return {}

        status = {}
        for priority, alloc in self._allocations[key].items():
            status[priority] = {
                "allocated": alloc.allocated_qty,
                "consumed": alloc.consumed_qty,
                "available": alloc.available_qty,
                "utilization": alloc.utilization,
            }

        return status

    def get_consumption_feedback(self) -> Dict[str, Any]:
        """
        Get consumption feedback for the current period.

        This data feeds into the next tGNN allocation cycle.
        """
        if not self._consumption_history:
            return {"status": "no_data"}

        total_orders = len(self._consumption_history)
        fully_fulfilled = sum(1 for r in self._consumption_history if r.fully_fulfilled)
        partial_fills = sum(
            1 for r in self._consumption_history
            if not r.fully_fulfilled and r.fulfilled_qty > 0
        )

        # OTIF metrics
        on_time_count = sum(1 for r in self._consumption_history if r.on_time)
        in_full_count = sum(1 for r in self._consumption_history if r.in_full)
        otif_count = sum(
            1 for r in self._consumption_history
            if r.on_time and r.in_full
        )

        # Consumption by priority
        consumption_by_priority: Dict[int, float] = {}
        for result in self._consumption_history:
            for priority, qty in result.consumption_by_priority.items():
                consumption_by_priority[priority] = (
                    consumption_by_priority.get(priority, 0) + qty
                )

        # Cross-priority consumption (orders consuming from lower tiers)
        cross_priority_consumption = sum(
            qty for result in self._consumption_history
            for priority, qty in result.consumption_by_priority.items()
            if priority != result.order_priority
        )

        return {
            "period_start": self._period_start.isoformat() if self._period_start else None,
            "period_end": self._period_end.isoformat() if self._period_end else None,
            "total_orders": total_orders,
            "fully_fulfilled": fully_fulfilled,
            "partial_fills": partial_fills,
            "fulfillment_rate": fully_fulfilled / total_orders if total_orders > 0 else 0,
            "otif_metrics": {
                "on_time_rate": on_time_count / total_orders if total_orders > 0 else 0,
                "in_full_rate": in_full_count / total_orders if total_orders > 0 else 0,
                "otif_rate": otif_count / total_orders if total_orders > 0 else 0,
            },
            "consumption_by_priority": consumption_by_priority,
            "cross_priority_consumption": cross_priority_consumption,
            "allocation_utilization": self._get_overall_utilization(),
        }

    def _get_overall_utilization(self) -> Dict[int, float]:
        """Get overall utilization by priority across all products/sites"""
        utilization: Dict[int, Dict[str, float]] = {}

        for allocs in self._allocations.values():
            for priority, alloc in allocs.items():
                if priority not in utilization:
                    utilization[priority] = {"allocated": 0, "consumed": 0}
                utilization[priority]["allocated"] += alloc.allocated_qty
                utilization[priority]["consumed"] += alloc.consumed_qty

        return {
            p: u["consumed"] / u["allocated"] if u["allocated"] > 0 else 0
            for p, u in utilization.items()
        }

    def reset_for_new_period(self):
        """
        Reset for a new allocation period.

        Clears consumption history and prepares for new allocations.
        """
        # Archive feedback before clearing
        feedback = self.get_consumption_feedback()
        logger.info(f"Period feedback: {feedback}")

        self._consumption_history.clear()
        self._allocations.clear()
        self._period_start = None
        self._period_end = None


# ---------------------------------------------------------------------------
# Bridge: AllocationCommit → PowellAllocation + PriorityAllocation
# ---------------------------------------------------------------------------

def materialize_allocation_commit(
    db,
    allocation_commit,
    config_id: int,
    dc_location_id: str,
    deactivate_prior: bool = True,
):
    """
    Materialize an AllocationCommit's JSON allocations into:
    1. PowellAllocation ORM rows (persisted to DB)
    2. PriorityAllocation in-memory objects (for AllocationService.set_allocations)

    Bridge logic:
    - Aggregate entitlement_qty by (sku, priority) across customers
    - Parse ISO week time_bucket → 7 daily PowellAllocation rows
    - Optionally delete prior cascade-sourced rows for the same date range

    Args:
        db: SQLAlchemy sync Session
        allocation_commit: AllocationCommit ORM object (must have .allocations JSON
            and .status)
        config_id: supply_chain_configs.id
        dc_location_id: location_id string for the DC site
        deactivate_prior: if True, delete existing cascade-sourced rows for same
            date range before inserting

    Returns:
        Tuple of (list of PowellAllocation ORM objects, list of PriorityAllocation)
    """
    from collections import defaultdict
    from app.models.powell_allocation import PowellAllocation

    # 1. Status gate — only materialize accepted/submitted commits
    valid_statuses = {"accepted", "submitted", "auto_submitted"}
    status_val = (
        allocation_commit.status.value
        if hasattr(allocation_commit.status, "value")
        else str(allocation_commit.status)
    )
    if status_val not in valid_statuses:
        logger.info(
            f"Skipping AllocationCommit {allocation_commit.id} — "
            f"status '{status_val}' not in {valid_statuses}"
        )
        return [], []

    allocations_json = allocation_commit.allocations
    if not allocations_json:
        return [], []

    # 2. Aggregate entitlement_qty by (sku, priority)
    agg = defaultdict(float)
    for entry in allocations_json:
        sku = entry.get("sku") or entry.get("product_id", "")
        priority = entry.get("priority", 3)
        agg[(sku, priority)] += entry.get("entitlement_qty", 0.0)

    # 3. Parse time_bucket from first entry (default to current ISO week if absent)
    sample_entry = allocations_json[0]
    time_bucket = sample_entry.get("time_bucket", "")
    if time_bucket and "W" in time_bucket:
        year_str, week_str = time_bucket.split("-W")
        year, week = int(year_str), int(week_str)
        week_start = datetime.strptime(f"{year}-W{week:02d}-1", "%G-W%V-%u").date()
    else:
        # Default to the Monday of the current ISO week
        from app.core.clock import config_today_sync
        today = config_today_sync(config_id, db)
        week_start = today - timedelta(days=today.weekday())
        logger.info(
            f"AllocationCommit {allocation_commit.id} has no time_bucket, "
            f"defaulting to current week starting {week_start}"
        )
    week_end = week_start + timedelta(days=6)

    # 4. Delete prior cascade-sourced rows for same date range
    if deactivate_prior:
        deleted = (
            db.query(PowellAllocation)
            .filter(
                PowellAllocation.config_id == config_id,
                PowellAllocation.site_id == dc_location_id,
                PowellAllocation.allocation_source == "cascade",
                PowellAllocation.valid_from >= datetime.combine(week_start, datetime.min.time()),
                PowellAllocation.valid_from <= datetime.combine(week_end, datetime.max.time()),
            )
            .delete(synchronize_session="fetch")
        )
        if deleted:
            logger.info(f"Deleted {deleted} prior cascade PowellAllocation rows")

    # 5. Create daily PowellAllocation rows + in-memory PriorityAllocation
    powell_rows = []
    priority_allocs = []

    for (sku, priority), weekly_qty in sorted(agg.items()):
        daily_qty = round(weekly_qty / 7.0, 2)

        for day_offset in range(7):
            day = week_start + timedelta(days=day_offset)
            valid_from = datetime.combine(day, datetime.min.time())
            valid_to = datetime.combine(day, datetime.max.time())

            row = PowellAllocation(
                config_id=config_id,
                product_id=sku,
                site_id=dc_location_id,
                priority=priority,
                allocated_qty=daily_qty,
                consumed_qty=0.0,
                reserved_qty=0.0,
                allocation_source="cascade",
                allocation_cadence="daily",
                valid_from=valid_from,
                valid_to=valid_to,
                is_active=True,
            )
            db.add(row)
            powell_rows.append(row)

        # In-memory PriorityAllocation for AllocationService
        priority_allocs.append(PriorityAllocation(
            priority=priority,
            product_id=sku,
            site_id=dc_location_id,
            allocated_qty=weekly_qty,
            valid_from=week_start,
            valid_to=week_end,
            generated_by="cascade",
        ))

    db.flush()
    logger.info(
        f"Materialized AllocationCommit {allocation_commit.id}: "
        f"{len(powell_rows)} PowellAllocation rows, "
        f"{len(priority_allocs)} PriorityAllocation objects"
    )
    return powell_rows, priority_allocs
