"""
ATP Executor with TRM for Allocated Available-to-Promise (AATP)

Uses a narrow TRM model to execute ATP decisions within the constraints
of priority allocations generated by tGNN.

TRM Scope (narrow):
- Given: allocations, current order, inventory state
- Decide: Can fulfill? How much? From which allocation tiers?

This is NOT a general-purpose supply chain brain. It's a specialized
"skill" for ATP decisions that plays to TRM strengths:
- Narrow scope, few variables
- Short horizon (immediate decision)
- Fast feedback (order fulfilled or not)
- Clear objective (maximize fill rate within allocation rules)

References:
- Conversation with Claude on TRM scope and AATP architecture
- Powell VFA for narrow execution decisions
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any
from enum import Enum
import numpy as np
import logging

from .allocation_service import (
    AllocationService,
    AllocationConfig,
    ConsumptionResult,
    PriorityAllocation,
    UnfulfillableOrderAction,
)
from .engines.aatp_engine import AATPEngine, AATPConfig, Order as EngineOrder, Priority

logger = logging.getLogger(__name__)


@dataclass
class ATPRequest:
    """Request for ATP check"""
    order_id: str
    product_id: str
    location_id: str
    requested_qty: float
    priority: int
    requested_date: Optional[str] = None
    demand_source: Optional[str] = None
    customer_id: Optional[str] = None

    # For multi-line orders
    line_id: Optional[str] = None


@dataclass
class ATPResponse:
    """Response from ATP check"""
    order_id: str
    line_id: Optional[str]

    # Availability
    can_fulfill: bool
    available_qty: float
    promised_qty: float
    promised_date: Optional[str] = None

    # Source of fulfillment
    fulfillment_source: str = "allocation"  # "allocation", "safety_stock", "production"
    consumption_breakdown: Dict[int, float] = field(default_factory=dict)

    # Confidence (from TRM)
    confidence: float = 1.0
    reasoning: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "order_id": self.order_id,
            "line_id": self.line_id,
            "can_fulfill": self.can_fulfill,
            "available_qty": self.available_qty,
            "promised_qty": self.promised_qty,
            "promised_date": self.promised_date,
            "fulfillment_source": self.fulfillment_source,
            "consumption_breakdown": self.consumption_breakdown,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
        }


@dataclass
class ATPState:
    """
    State representation for TRM ATP decisions.

    This is the narrow state space that the TRM operates on.
    """
    # Order context
    order_priority: int
    requested_qty: float

    # Allocation state (by priority tier)
    allocation_available: Dict[int, float]  # priority -> available qty

    # Inventory context (from tGNN)
    current_inventory: float
    pipeline_inventory: float
    safety_stock_level: float

    # Demand context
    demand_forecast: float
    demand_uncertainty: float

    def to_features(self) -> np.ndarray:
        """Convert to feature vector for TRM"""
        # Fixed-size feature vector
        features = [
            float(self.order_priority),
            self.requested_qty,
            self.current_inventory,
            self.pipeline_inventory,
            self.safety_stock_level,
            self.demand_forecast,
            self.demand_uncertainty,
        ]

        # Add allocation features (assume max 5 priorities)
        for p in range(1, 6):
            features.append(self.allocation_available.get(p, 0.0))

        return np.array(features, dtype=np.float32)


class ATPExecutorTRM:
    """
    TRM-based ATP Executor for Allocated Available-to-Promise.

    Architecture:
    - tGNN provides: allocations, inventory context, demand signals
    - TRM decides: fulfillment feasibility and quantity within allocation rules

    The TRM is trained on historical ATP decisions and their outcomes.
    It learns to make fast, accurate decisions within the allocation framework.
    """

    def __init__(
        self,
        allocation_service: AllocationService,
        trm_model: Optional[Any] = None,
        use_heuristic_fallback: bool = True,
        aatp_engine: Optional[AATPEngine] = None,
        db: Optional[Any] = None,
        config_id: Optional[int] = None,
    ):
        """
        Initialize ATP Executor.

        Args:
            allocation_service: Service managing priority allocations
            trm_model: Trained TRM model for ATP decisions (optional)
            use_heuristic_fallback: Use rules-based fallback if TRM unavailable
            aatp_engine: Deterministic AATP engine (optional, used for heuristic)
            db: Optional SQLAlchemy Session for persisting decisions
            config_id: Optional config_id for DB persistence
        """
        self.allocation_service = allocation_service
        self._engine = aatp_engine
        self.trm_model = trm_model
        self.use_heuristic_fallback = use_heuristic_fallback
        self.db = db
        self.config_id = config_id

        # Decision history for TRM training
        self._decision_history: List[Dict[str, Any]] = []

        # Performance metrics
        self._metrics = {
            "total_requests": 0,
            "fulfilled_requests": 0,
            "partial_fills": 0,
            "trm_decisions": 0,
            "heuristic_decisions": 0,
        }

    def check_atp(
        self,
        request: ATPRequest,
        inventory_context: Optional[Dict[str, float]] = None
    ) -> ATPResponse:
        """
        Check ATP for an order request.

        This is the main entry point for ATP decisions.

        Args:
            request: ATP request details
            inventory_context: Current inventory state (from tGNN or cache)

        Returns:
            ATPResponse with fulfillment decision
        """
        self._metrics["total_requests"] += 1

        # Build state for TRM
        state = self._build_atp_state(request, inventory_context)

        # Get decision from TRM or heuristic
        if self.trm_model is not None:
            response = self._trm_decision(request, state)
            self._metrics["trm_decisions"] += 1
        elif self.use_heuristic_fallback:
            response = self._heuristic_decision(request, state)
            self._metrics["heuristic_decisions"] += 1
        else:
            response = ATPResponse(
                order_id=request.order_id,
                line_id=request.line_id,
                can_fulfill=False,
                available_qty=0,
                promised_qty=0,
                reasoning="No TRM model available and heuristic disabled",
            )

        # Record for training
        self._record_decision(request, state, response)

        return response

    def commit_atp(self, request: ATPRequest, response: ATPResponse) -> ConsumptionResult:
        """
        Commit an ATP decision by consuming from allocations.

        Called when order is confirmed after ATP check.

        Args:
            request: Original ATP request
            response: ATP response to commit

        Returns:
            ConsumptionResult from allocation service
        """
        if not response.can_fulfill or response.promised_qty == 0:
            return ConsumptionResult(
                order_id=request.order_id,
                order_priority=request.priority,
                requested_qty=request.requested_qty,
                fulfilled_qty=0,
            )

        result = self.allocation_service.consume_for_order(
            order_id=request.order_id,
            product_id=request.product_id,
            location_id=request.location_id,
            requested_qty=response.promised_qty,
            order_priority=request.priority,
            demand_source=request.demand_source,
        )

        if result.fulfilled_qty > 0:
            self._metrics["fulfilled_requests"] += 1
        if result.fulfilled_qty > 0 and not result.fully_fulfilled:
            self._metrics["partial_fills"] += 1

        return result

    def _build_atp_state(
        self,
        request: ATPRequest,
        inventory_context: Optional[Dict[str, float]] = None
    ) -> ATPState:
        """Build state representation for TRM"""
        # Get allocation status
        alloc_status = self.allocation_service.get_allocation_status(
            request.product_id, request.location_id
        )

        allocation_available = {
            p: status.get("available", 0)
            for p, status in alloc_status.items()
        }

        # Default inventory context
        inv_ctx = inventory_context or {}

        return ATPState(
            order_priority=request.priority,
            requested_qty=request.requested_qty,
            allocation_available=allocation_available,
            current_inventory=inv_ctx.get("current_inventory", 0),
            pipeline_inventory=inv_ctx.get("pipeline_inventory", 0),
            safety_stock_level=inv_ctx.get("safety_stock", 0),
            demand_forecast=inv_ctx.get("demand_forecast", 0),
            demand_uncertainty=inv_ctx.get("demand_uncertainty", 0),
        )

    def _trm_decision(self, request: ATPRequest, state: ATPState) -> ATPResponse:
        """
        Get ATP decision from TRM model.

        TRM outputs:
        - can_fulfill: binary
        - fulfill_qty: continuous
        - confidence: 0-1
        """
        try:
            features = state.to_features()

            # TRM inference — returns dict with action_logits, fulfill_qty, confidence, value
            output = self.trm_model.predict(features.reshape(1, -1))

            action_idx = int(np.argmax(output["action_logits"][0]))
            can_fulfill = action_idx in (0, 1)  # fulfill or partial
            fulfill_qty = max(0, min(float(output["fulfill_qty"][0, 0]) * request.requested_qty,
                                     request.requested_qty))
            confidence = float(np.clip(output["confidence"][0, 0], 0, 1))

            # Determine consumption breakdown using heuristic
            # (TRM decides quantity, rules determine which tiers)
            breakdown = self._calculate_consumption_breakdown(
                state, request.priority, fulfill_qty
            )

            return ATPResponse(
                order_id=request.order_id,
                line_id=request.line_id,
                can_fulfill=can_fulfill and fulfill_qty > 0,
                available_qty=sum(state.allocation_available.values()),
                promised_qty=fulfill_qty if can_fulfill else 0,
                consumption_breakdown=breakdown,
                confidence=confidence,
                reasoning=f"TRM decision with confidence {confidence:.2f}",
            )

        except Exception as e:
            logger.warning(f"TRM inference failed: {e}, falling back to heuristic")
            return self._heuristic_decision(request, state)

    def _heuristic_decision(self, request: ATPRequest, state: ATPState) -> ATPResponse:
        """
        Heuristic ATP decision when TRM is unavailable.

        Delegates to AATPEngine if available, otherwise implements
        the consumption logic directly:
        1. Own tier first
        2. Bottom-up from lowest priority
        3. Cannot consume above own tier
        """
        # Delegate to deterministic engine if available
        if self._engine is not None:
            try:
                from datetime import date
                engine_order = EngineOrder(
                    order_id=request.order_id,
                    product_id=request.product_id,
                    location_id=request.location_id,
                    requested_qty=request.requested_qty,
                    requested_date=date.today(),
                    priority=Priority.from_value(request.priority),
                    customer_id=request.customer_id or "",
                )
                engine_result = self._engine.check_availability(engine_order)
                breakdown = {p.value: q for p, q in engine_result.consumption_detail}
                return ATPResponse(
                    order_id=request.order_id,
                    line_id=request.line_id,
                    can_fulfill=engine_result.can_fulfill_full or engine_result.available_qty > 0,
                    available_qty=engine_result.available_qty,
                    promised_qty=engine_result.available_qty,
                    consumption_breakdown=breakdown,
                    confidence=1.0,
                    reasoning=engine_result.recommendation or "Engine-based AATP decision",
                )
            except Exception as e:
                logger.warning(f"AATPEngine delegation failed: {e}, using inline heuristic")

        # Build consumption sequence
        num_priorities = max(state.allocation_available.keys()) if state.allocation_available else 5
        sequence = self._build_consumption_sequence(request.priority, num_priorities)

        # Calculate available following the sequence
        available_qty = 0.0
        breakdown: Dict[int, float] = {}
        remaining_need = request.requested_qty

        for priority in sequence:
            if remaining_need <= 0:
                break

            tier_available = state.allocation_available.get(priority, 0)
            consume_from_tier = min(tier_available, remaining_need)

            if consume_from_tier > 0:
                breakdown[priority] = consume_from_tier
                available_qty += consume_from_tier
                remaining_need -= consume_from_tier

        can_fulfill = available_qty > 0
        promised_qty = available_qty if can_fulfill else 0

        # Build reasoning
        if can_fulfill:
            if available_qty >= request.requested_qty:
                reasoning = f"Full fulfillment from tiers: {list(breakdown.keys())}"
            else:
                fill_rate = available_qty / request.requested_qty
                reasoning = f"Partial fulfillment ({fill_rate:.0%}) from tiers: {list(breakdown.keys())}"
        else:
            reasoning = "No allocation available in eligible tiers"

        return ATPResponse(
            order_id=request.order_id,
            line_id=request.line_id,
            can_fulfill=can_fulfill,
            available_qty=sum(state.allocation_available.values()),
            promised_qty=promised_qty,
            consumption_breakdown=breakdown,
            confidence=1.0,  # Heuristic is deterministic
            reasoning=reasoning,
        )

    def _build_consumption_sequence(self, order_priority: int, num_priorities: int) -> List[int]:
        """
        Build consumption sequence per AATP rules.

        1. Own tier first
        2. Lowest tier (highest number)
        3. Work upward toward own tier
        4. Cannot go above own tier
        """
        sequence = [order_priority]  # Own tier first

        # Then from bottom up, stopping at own tier
        for p in range(num_priorities, order_priority, -1):
            if p != order_priority:
                sequence.append(p)

        return sequence

    def _calculate_consumption_breakdown(
        self,
        state: ATPState,
        order_priority: int,
        fulfill_qty: float
    ) -> Dict[int, float]:
        """Calculate which tiers will be consumed for a given fulfillment qty"""
        num_priorities = max(state.allocation_available.keys()) if state.allocation_available else 5
        sequence = self._build_consumption_sequence(order_priority, num_priorities)

        breakdown: Dict[int, float] = {}
        remaining = fulfill_qty

        for priority in sequence:
            if remaining <= 0:
                break

            available = state.allocation_available.get(priority, 0)
            consume = min(available, remaining)

            if consume > 0:
                breakdown[priority] = consume
                remaining -= consume

        return breakdown

    def _record_decision(
        self,
        request: ATPRequest,
        state: ATPState,
        response: ATPResponse
    ):
        """Record decision for TRM training feedback"""
        record = {
            "request": {
                "order_id": request.order_id,
                "product_id": request.product_id,
                "location_id": request.location_id,
                "requested_qty": request.requested_qty,
                "priority": request.priority,
            },
            "state_features": state.to_features().tolist(),
            "response": response.to_dict(),
            "timestamp": str(np.datetime64('now')),
        }

        self._decision_history.append(record)

        # Keep bounded history
        if len(self._decision_history) > 10000:
            self._decision_history = self._decision_history[-10000:]

        # Persist to DB if session available
        self._persist_decision(request, state, response)

    def _persist_decision(
        self,
        request: ATPRequest,
        state: ATPState,
        response: ATPResponse
    ):
        """Persist decision to powell_atp_decisions table."""
        if self.db is None or self.config_id is None:
            return
        try:
            from app.models.powell_decisions import PowellATPDecision
            row = PowellATPDecision(
                config_id=self.config_id,
                order_id=request.order_id,
                product_id=request.product_id,
                location_id=request.location_id,
                requested_qty=request.requested_qty,
                order_priority=request.priority,
                can_fulfill=response.can_fulfill,
                promised_qty=response.promised_qty,
                consumption_breakdown={str(k): v for k, v in (response.consumption_breakdown or {}).items()},
                state_features=state.to_features().tolist(),
                decision_method="trm" if self.trm_model else "heuristic",
                confidence=response.confidence,
            )
            self.db.add(row)
        except Exception as e:
            logger.warning(f"Failed to persist ATP decision: {e}")

    def get_training_data(self) -> List[Dict[str, Any]]:
        """
        Get decision history for TRM training.

        Returns data that can be used for supervised learning
        or reinforcement learning with outcomes.
        """
        return self._decision_history

    def get_metrics(self) -> Dict[str, Any]:
        """Get executor performance metrics"""
        total = self._metrics["total_requests"]
        return {
            **self._metrics,
            "fulfillment_rate": (
                self._metrics["fulfilled_requests"] / total if total > 0 else 0
            ),
            "partial_fill_rate": (
                self._metrics["partial_fills"] / total if total > 0 else 0
            ),
            "trm_usage_rate": (
                self._metrics["trm_decisions"] / total if total > 0 else 0
            ),
        }


class MultiSiteATPExecutorTRM:
    """
    ATP Executor that can search across multiple sites.

    Per the architecture discussion, ATP runs per-site, but this wrapper
    can coordinate across sites when needed for multi-location fulfillment.
    """

    def __init__(
        self,
        site_executors: Dict[str, ATPExecutorTRM]
    ):
        """
        Initialize multi-site executor.

        Args:
            site_executors: Map of site_id -> ATPExecutorTRM
        """
        self.site_executors = site_executors

    def check_atp_multi_site(
        self,
        request: ATPRequest,
        preferred_sites: Optional[List[str]] = None
    ) -> Tuple[Optional[str], ATPResponse]:
        """
        Check ATP across multiple sites.

        Returns the best site and response.
        """
        best_site = None
        best_response = None

        sites_to_check = preferred_sites or list(self.site_executors.keys())

        for site_id in sites_to_check:
            if site_id not in self.site_executors:
                continue

            executor = self.site_executors[site_id]
            site_request = ATPRequest(
                order_id=request.order_id,
                product_id=request.product_id,
                location_id=site_id,
                requested_qty=request.requested_qty,
                priority=request.priority,
                requested_date=request.requested_date,
                demand_source=request.demand_source,
                line_id=request.line_id,
            )

            response = executor.check_atp(site_request)

            # Pick best response (highest promised qty)
            if best_response is None or response.promised_qty > best_response.promised_qty:
                best_site = site_id
                best_response = response

            # Stop if fully fulfilled
            if response.can_fulfill and response.promised_qty >= request.requested_qty:
                break

        if best_response is None:
            best_response = ATPResponse(
                order_id=request.order_id,
                line_id=request.line_id,
                can_fulfill=False,
                available_qty=0,
                promised_qty=0,
                reasoning="No sites available",
            )

        return best_site, best_response
