"""
S&OP GraphSAGE Training Data Generator (CFA Oracle)

Generates labeled training data for the S&OP GraphSAGE model by using the
existing Cost Function Approximation (Differential Evolution) optimizer as
a supervised oracle.

MOTIVATION (oracle training):
  The S&OP GraphSAGE learns to predict optimal policy parameters θ* from the
  supply network graph structure. Supervised training requires (graph, θ*) pairs.
  Where do the θ* labels come from?

  Answer: the CFA Oracle. It generates diverse synthetic supply chain network
  configurations, runs Differential Evolution (Powell's CFA method) to find the
  optimal policy parameters θ* for each, and records (graph_features, θ*) as a
  supervised training sample. The GraphSAGE is then trained to predict θ* from
  graph features alone — amortising the expensive DE optimization into a fast
  neural network forward pass at inference time.

  This is the same principle as:
  - AlphaCode: LLM trained on (problem, optimal_solution) pairs generated by
    a search algorithm
  - Stockfish: LLM trained on (position, Stockfish_eval) pairs

CFA POLICY PARAMETERS θ (per site):
  - safety_stock_multiplier: [0.5, 3.0]  scale SS targets relative to formula
  - service_level_target:    [0.80, 0.99]  service level to achieve
  - reorder_point_days:      [3, 21]  days before stockout to order
  - order_up_to_days:        [7, 60]  DOS target for replenishment
  - sourcing_split:          [0, 1]  fraction from primary vs backup supplier

  θ is a flat vector of all these parameters across all sites in the network.

DE OPTIMIZER:
  scipy.optimize.differential_evolution (global optimizer, no gradient required)
  Objective: E[total_cost] = Σ holding_cost + Σ stockout_cost + Σ ordering_cost
  Evaluated via Monte Carlo simulation over 30+ scenarios (fast simulation proxy).

TRAINING DATA FORMAT:
  Each SoPTrainingSample contains:
    node_features: [num_sites, node_feature_dim]   network structure + state
    edge_features: [num_lanes, edge_feature_dim]   lane attributes
    edge_index: [2, num_lanes]
    optimal_theta: Dict[site_id, PolicyParams]     DE-optimal parameters
    theta_vector: np.ndarray  flat θ* vector for direct regression
    objective_value: float    expected cost at θ*
    de_converged: bool        whether DE found a good solution

USAGE:
    oracle = SoPGraphSAGEOracle(seed=42)
    samples = oracle.generate_samples(
        num_scenarios=100,   # DE is slow (~1-3 min/scenario), parallelise if needed
        num_sites=(4, 12),   # Range for random network size
    )
    # → List[SoPTrainingSample]  for GraphSAGE supervised training
    # → Call SoPGraphSAGETrainer(samples).train() to fit the model

NOTE ON COMPUTE:
  Each DE run takes ~30-120s depending on network size and num_mc_scenarios.
  Use num_mc_scenarios=20 for quick experiments, 100+ for production quality.
  Parallelise with multiprocessing.Pool (each run is independent).
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:
    from scipy.optimize import differential_evolution, OptimizeResult
    SCIPY_AVAILABLE = True
except ImportError:  # pragma: no cover
    SCIPY_AVAILABLE = False
    differential_evolution = None  # type: ignore[assignment]


logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Policy parameter schema
# ---------------------------------------------------------------------------

@dataclass
class PolicyParams:
    """Optimal policy parameters for one site (θ per site)."""
    safety_stock_multiplier: float = 1.0   # [0.5, 3.0]
    service_level_target: float    = 0.95  # [0.80, 0.99]
    reorder_point_days: float      = 7.0   # [3, 21]
    order_up_to_days: float        = 21.0  # [7, 60]
    sourcing_split: float          = 0.7   # [0, 1] fraction from primary supplier

    def to_vector(self) -> np.ndarray:
        return np.array([
            self.safety_stock_multiplier,
            self.service_level_target,
            self.reorder_point_days,
            self.order_up_to_days,
            self.sourcing_split,
        ], dtype=np.float32)

    @classmethod
    def from_vector(cls, v: np.ndarray) -> "PolicyParams":
        return cls(
            safety_stock_multiplier=float(v[0]),
            service_level_target=float(v[1]),
            reorder_point_days=float(v[2]),
            order_up_to_days=float(v[3]),
            sourcing_split=float(v[4]),
        )

    PARAM_DIM: int = 5

    BOUNDS: List[Tuple[float, float]] = field(default_factory=lambda: [
        (0.5, 3.0),   # safety_stock_multiplier
        (0.80, 0.99), # service_level_target
        (3.0, 21.0),  # reorder_point_days
        (7.0, 60.0),  # order_up_to_days
        (0.0, 1.0),   # sourcing_split
    ])


# Class-level bounds (not instance field to avoid dataclass issues)
POLICY_BOUNDS: List[Tuple[float, float]] = [
    (0.5, 3.0),
    (0.80, 0.99),
    (3.0, 21.0),
    (7.0, 60.0),
    (0.0, 1.0),
]


@dataclass
class SoPNetworkSite:
    """A site in the S&OP planning network."""
    site_id: str
    master_type: str               # "VENDOR", "INVENTORY", "MANUFACTURER", "CUSTOMER"
    avg_weekly_demand: float
    demand_variability_cv: float   # coefficient of variation
    avg_lead_time_weeks: float
    lead_time_variability_cv: float
    on_hand_qty: float
    unit_cost: float
    annual_holding_rate: float     # e.g., 0.25
    stockout_cost_per_unit: float
    ordering_cost: float
    criticality_score: float       # 0-1, network criticality


@dataclass
class SoPNetworkLane:
    """Transportation lane in the S&OP network."""
    from_site: str
    to_site: str
    lead_time_weeks: float
    transport_cost_per_unit: float
    reliability: float             # on-time delivery rate [0, 1]
    capacity_units_per_week: float


@dataclass
class SoPNetwork:
    """Complete supply chain network for S&OP planning."""
    network_id: str
    sites: List[SoPNetworkSite]
    lanes: List[SoPNetworkLane]
    planning_horizon_weeks: int = 26


@dataclass
class SoPTrainingSample:
    """
    One oracle-generated training sample for S&OP GraphSAGE.

    node_features: [num_sites, node_feature_dim=14]
    edge_features: [num_lanes, edge_feature_dim=4]
    edge_index: [2, num_lanes]
    optimal_theta: Dict[site_id, PolicyParams]  per-site DE-optimal parameters
    theta_vector: np.ndarray [num_sites * PARAM_DIM]  flat concatenated θ*
    objective_value: float  E[total_cost] at θ* (lower = better)
    de_converged: bool  whether DE solved the problem satisfactorily
    """
    sample_id: str
    network: SoPNetwork
    node_features: np.ndarray    # [num_sites, 14]
    edge_features: np.ndarray    # [num_lanes, 4]
    edge_index: np.ndarray       # [2, num_lanes]
    optimal_theta: Dict[str, PolicyParams]
    theta_vector: np.ndarray     # [num_sites * PARAM_DIM]
    objective_value: float
    de_converged: bool

    NODE_FEATURE_DIM: int = 14
    EDGE_FEATURE_DIM: int = 4


# ---------------------------------------------------------------------------
# GraphSAGE Trainer stub (supervised training on oracle samples)
# ---------------------------------------------------------------------------

class SoPGraphSAGETrainer:
    """
    Trains the S&OP GraphSAGE to predict θ* from network graph features.

    Uses the samples generated by SoPGraphSAGEOracle as (X, y) pairs:
      X = (node_features, edge_features, edge_index)  ← graph structure
      y = theta_vector                                 ← DE-optimal parameters

    Loss = MSE(predicted_theta, oracle_theta)  per policy parameter
    Additionally tracks: parameter-wise MAE, convergence curve.

    Integration: After training, call predict_theta(network) which runs the
    GraphSAGE forward pass and returns the predicted θ for each site.
    This replaces the weekly DE run with a ~1ms neural network inference.

    NOTE: Full integration with the existing ScalableGraphSAGE model in
    backend/app/models/gnn/scalable_graphsage.py is pending. This trainer
    currently uses a lightweight MLP-on-node-features as a stand-in;
    replace _build_model() with the full GraphSAGE for production use.
    """

    def __init__(
        self,
        samples: List[SoPTrainingSample],
        node_feature_dim: int = SoPTrainingSample.NODE_FEATURE_DIM,
        hidden_dim: int = 128,
        num_layers: int = 3,
        learning_rate: float = 1e-3,
    ) -> None:
        try:
            import torch
            import torch.nn as nn
            self.torch = torch
            self.nn = nn
            self._torch_available = True
        except ImportError:
            logger.warning("PyTorch not available — training disabled")
            self._torch_available = False

        self.samples = [s for s in samples if s.de_converged]
        logger.info(
            "SoPGraphSAGETrainer: %d/%d converged samples available for training",
            len(self.samples), len(samples),
        )
        self.node_feature_dim = node_feature_dim
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.lr = learning_rate
        self.model = None

    def train(
        self,
        epochs: int = 50,
        batch_size: int = 16,
        val_split: float = 0.1,
    ) -> Dict[str, Any]:
        """
        Train GraphSAGE on oracle samples.
        Returns training metrics dict: {train_loss, val_loss, epoch_losses}.
        """
        if not self._torch_available:
            return {"error": "PyTorch not available"}
        if len(self.samples) < 2:
            return {"error": "insufficient converged samples for training"}

        torch = self.torch
        nn = self.nn

        # Determine output dimension from first sample
        theta_dim = self.samples[0].theta_vector.shape[0]
        self.model = self._build_model(self.node_feature_dim, self.hidden_dim, theta_dim)
        optimizer = torch.optim.Adam(self.model.parameters(), lr=self.lr)
        loss_fn = nn.MSELoss()

        # Train/val split
        split_idx = max(1, int(len(self.samples) * (1 - val_split)))
        train_samples = self.samples[:split_idx]
        val_samples   = self.samples[split_idx:]

        epoch_losses: List[float] = []
        for epoch in range(epochs):
            self.model.train()
            epoch_loss = 0.0
            idx = list(range(len(train_samples)))
            np.random.shuffle(idx)

            for start in range(0, len(idx), batch_size):
                batch_idx = idx[start: start + batch_size]
                X_batch = torch.stack([
                    torch.tensor(train_samples[i].node_features.mean(axis=0), dtype=torch.float32)
                    for i in batch_idx
                ])
                y_batch = torch.stack([
                    torch.tensor(train_samples[i].theta_vector, dtype=torch.float32)
                    for i in batch_idx
                ])

                optimizer.zero_grad()
                y_pred = self.model(X_batch)
                loss = loss_fn(y_pred, y_batch)
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()

            avg_loss = epoch_loss / max(len(train_samples) // batch_size, 1)
            epoch_losses.append(avg_loss)
            if epoch % 10 == 0:
                logger.debug("SoPGraphSAGETrainer epoch %d/%d loss=%.4f", epoch + 1, epochs, avg_loss)

        # Validation loss
        self.model.eval()
        val_loss = 0.0
        if val_samples:
            with torch.no_grad():
                X_val = torch.stack([
                    torch.tensor(s.node_features.mean(axis=0), dtype=torch.float32)
                    for s in val_samples
                ])
                y_val = torch.stack([
                    torch.tensor(s.theta_vector, dtype=torch.float32)
                    for s in val_samples
                ])
                val_loss = float(loss_fn(self.model(X_val), y_val).item())

        return {
            "train_loss": epoch_losses[-1] if epoch_losses else None,
            "val_loss": val_loss,
            "epoch_losses": epoch_losses,
            "num_train_samples": len(train_samples),
            "num_val_samples": len(val_samples),
            "theta_dim": theta_dim,
        }

    def predict_theta(self, network: SoPNetwork) -> Dict[str, PolicyParams]:
        """
        Predict optimal policy parameters for a new network in ~1ms.
        Replaces weekly DE optimization at inference time.
        """
        if self.model is None:
            raise RuntimeError("Model not trained — call train() first")

        torch = self.torch
        S = len(network.sites)
        feat_oracle = SoPGraphSAGEOracle.__new__(SoPGraphSAGEOracle)
        feat_oracle.rng = np.random.default_rng(0)
        node_features, _, _ = feat_oracle._build_graph_features(network)

        x = torch.tensor(node_features.mean(axis=0), dtype=torch.float32).unsqueeze(0)
        with torch.no_grad():
            theta_pred = self.model(x).squeeze(0).numpy()

        param_dim = PolicyParams.PARAM_DIM
        result: Dict[str, PolicyParams] = {}
        for i, site in enumerate(network.sites):
            start = i * param_dim
            result[site.site_id] = PolicyParams.from_vector(
                theta_pred[start: start + param_dim]
            )
        return result

    def _build_model(self, input_dim: int, hidden_dim: int, output_dim: int):
        """Build a lightweight MLP as a stand-in for the full GraphSAGE."""
        nn = self.nn
        layers = [nn.Linear(input_dim, hidden_dim), nn.ReLU(), nn.Dropout(0.1)]
        for _ in range(self.num_layers - 2):
            layers += [nn.Linear(hidden_dim, hidden_dim), nn.ReLU(), nn.Dropout(0.1)]
        layers.append(nn.Linear(hidden_dim, output_dim))
        return nn.Sequential(*layers)

    @classmethod
    async def from_corpus(
        cls,
        db,
        config_id: int,
        hidden_dim: int = 128,
        num_layers: int = 3,
        learning_rate: float = 1e-3,
    ) -> "SoPGraphSAGETrainer":
        """Load Layer 4 samples from the unified training corpus.

        Preferred entry point for provisioning. Consumes samples produced
        by the corpus aggregator (TRM decisions rolled up by scenario with
        inferred theta*), not the orphan synthetic network sampler.

        See docs/internal/architecture/UNIFIED_TRAINING_CORPUS.md
        """
        from app.services.training_corpus import TrainingCorpusService

        service = TrainingCorpusService(db)
        corpus_samples = await service.get_samples(config_id=config_id, layer=4.0)

        # Convert corpus samples to legacy SoPTrainingSample format
        converted: List[SoPTrainingSample] = []
        for cs in corpus_samples:
            data = cs.get("sample_data", {})
            theta_star_by_site = data.get("theta_star", {})
            if not theta_star_by_site:
                continue

            # Build theta_vector by concatenating per-site policy params
            theta_list: List[float] = []
            for site_id, params in sorted(theta_star_by_site.items()):
                theta_list.extend([
                    params.get("safety_stock_multiplier", 1.0),
                    params.get("service_level_target", 0.95),
                    params.get("reorder_point_days", 7.0),
                    params.get("order_up_to_days", 21.0),
                    params.get("sourcing_split", 0.7),
                ])

            if not theta_list:
                continue

            num_sites = len(theta_star_by_site)
            # Build placeholder node features [num_sites, 14] from sample metadata
            node_feats = np.zeros((num_sites, SoPTrainingSample.NODE_FEATURE_DIM), dtype=np.float32)
            edge_feats = np.zeros((0, SoPTrainingSample.EDGE_FEATURE_DIM), dtype=np.float32)
            edge_index = np.zeros((2, 0), dtype=np.int64)

            converted.append(SoPTrainingSample(
                sample_id=str(uuid.uuid4()),
                network=SoPNetwork(
                    network_id=cs.get("scenario_id", ""),
                    sites=[],
                    lanes=[],
                ),
                node_features=node_feats,
                edge_features=edge_feats,
                edge_index=edge_index,
                optimal_theta={},
                theta_vector=np.array(theta_list, dtype=np.float32),
                objective_value=data.get("objective_value", 0.0),
                de_converged=True,  # corpus samples are pre-validated
            ))

        logger.info(
            "SoPGraphSAGETrainer.from_corpus: loaded %d/%d samples for config %d",
            len(converted), len(corpus_samples), config_id,
        )

        trainer = cls(
            samples=converted,
            hidden_dim=hidden_dim,
            num_layers=num_layers,
            learning_rate=learning_rate,
        )
        return trainer
