"""
S&OP GraphSAGE Training Data Generator (CFA Oracle)

Generates labeled training data for the S&OP GraphSAGE model by using the
existing Cost Function Approximation (Differential Evolution) optimizer as
a supervised oracle.

MOTIVATION (oracle training):
  The S&OP GraphSAGE learns to predict optimal policy parameters θ* from the
  supply network graph structure. Supervised training requires (graph, θ*) pairs.
  Where do the θ* labels come from?

  Answer: the CFA Oracle. It generates diverse synthetic supply chain network
  configurations, runs Differential Evolution (Powell's CFA method) to find the
  optimal policy parameters θ* for each, and records (graph_features, θ*) as a
  supervised training sample. The GraphSAGE is then trained to predict θ* from
  graph features alone — amortising the expensive DE optimization into a fast
  neural network forward pass at inference time.

  This is the same principle as:
  - AlphaCode: LLM trained on (problem, optimal_solution) pairs generated by
    a search algorithm
  - Stockfish: LLM trained on (position, Stockfish_eval) pairs

CFA POLICY PARAMETERS θ (per site):
  - safety_stock_multiplier: [0.5, 3.0]  scale SS targets relative to formula
  - service_level_target:    [0.80, 0.99]  service level to achieve
  - reorder_point_days:      [3, 21]  days before stockout to order
  - order_up_to_days:        [7, 60]  DOS target for replenishment
  - sourcing_split:          [0, 1]  fraction from primary vs backup supplier

  θ is a flat vector of all these parameters across all sites in the network.

DE OPTIMIZER:
  scipy.optimize.differential_evolution (global optimizer, no gradient required)
  Objective: E[total_cost] = Σ holding_cost + Σ stockout_cost + Σ ordering_cost
  Evaluated via Monte Carlo simulation over 30+ scenarios (fast simulation proxy).

TRAINING DATA FORMAT:
  Each SoPTrainingSample contains:
    node_features: [num_sites, node_feature_dim]   network structure + state
    edge_features: [num_lanes, edge_feature_dim]   lane attributes
    edge_index: [2, num_lanes]
    optimal_theta: Dict[site_id, PolicyParams]     DE-optimal parameters
    theta_vector: np.ndarray  flat θ* vector for direct regression
    objective_value: float    expected cost at θ*
    de_converged: bool        whether DE found a good solution

USAGE:
    oracle = SoPGraphSAGEOracle(seed=42)
    samples = oracle.generate_samples(
        num_scenarios=100,   # DE is slow (~1-3 min/scenario), parallelise if needed
        num_sites=(4, 12),   # Range for random network size
    )
    # → List[SoPTrainingSample]  for GraphSAGE supervised training
    # → Call SoPGraphSAGETrainer(samples).train() to fit the model

NOTE ON COMPUTE:
  Each DE run takes ~30-120s depending on network size and num_mc_scenarios.
  Use num_mc_scenarios=20 for quick experiments, 100+ for production quality.
  Parallelise with multiprocessing.Pool (each run is independent).
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:
    from scipy.optimize import differential_evolution, OptimizeResult
    SCIPY_AVAILABLE = True
except ImportError:  # pragma: no cover
    SCIPY_AVAILABLE = False
    differential_evolution = None  # type: ignore[assignment]

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Policy parameter schema
# ---------------------------------------------------------------------------

@dataclass
class PolicyParams:
    """Optimal policy parameters for one site (θ per site)."""
    safety_stock_multiplier: float = 1.0   # [0.5, 3.0]
    service_level_target: float    = 0.95  # [0.80, 0.99]
    reorder_point_days: float      = 7.0   # [3, 21]
    order_up_to_days: float        = 21.0  # [7, 60]
    sourcing_split: float          = 0.7   # [0, 1] fraction from primary supplier

    def to_vector(self) -> np.ndarray:
        return np.array([
            self.safety_stock_multiplier,
            self.service_level_target,
            self.reorder_point_days,
            self.order_up_to_days,
            self.sourcing_split,
        ], dtype=np.float32)

    @classmethod
    def from_vector(cls, v: np.ndarray) -> "PolicyParams":
        return cls(
            safety_stock_multiplier=float(v[0]),
            service_level_target=float(v[1]),
            reorder_point_days=float(v[2]),
            order_up_to_days=float(v[3]),
            sourcing_split=float(v[4]),
        )

    PARAM_DIM: int = 5

    BOUNDS: List[Tuple[float, float]] = field(default_factory=lambda: [
        (0.5, 3.0),   # safety_stock_multiplier
        (0.80, 0.99), # service_level_target
        (3.0, 21.0),  # reorder_point_days
        (7.0, 60.0),  # order_up_to_days
        (0.0, 1.0),   # sourcing_split
    ])


# Class-level bounds (not instance field to avoid dataclass issues)
POLICY_BOUNDS: List[Tuple[float, float]] = [
    (0.5, 3.0),
    (0.80, 0.99),
    (3.0, 21.0),
    (7.0, 60.0),
    (0.0, 1.0),
]


@dataclass
class SoPNetworkSite:
    """A site in the S&OP planning network."""
    site_id: str
    master_type: str               # "MARKET_SUPPLY", "INVENTORY", "MANUFACTURER", "MARKET_DEMAND"
    avg_weekly_demand: float
    demand_variability_cv: float   # coefficient of variation
    avg_lead_time_weeks: float
    lead_time_variability_cv: float
    on_hand_qty: float
    unit_cost: float
    annual_holding_rate: float     # e.g., 0.25
    stockout_cost_per_unit: float
    ordering_cost: float
    criticality_score: float       # 0-1, network criticality


@dataclass
class SoPNetworkLane:
    """Transportation lane in the S&OP network."""
    from_site: str
    to_site: str
    lead_time_weeks: float
    transport_cost_per_unit: float
    reliability: float             # on-time delivery rate [0, 1]
    capacity_units_per_week: float


@dataclass
class SoPNetwork:
    """Complete supply chain network for S&OP planning."""
    network_id: str
    sites: List[SoPNetworkSite]
    lanes: List[SoPNetworkLane]
    planning_horizon_weeks: int = 26


@dataclass
class SoPTrainingSample:
    """
    One oracle-generated training sample for S&OP GraphSAGE.

    node_features: [num_sites, node_feature_dim=14]
    edge_features: [num_lanes, edge_feature_dim=4]
    edge_index: [2, num_lanes]
    optimal_theta: Dict[site_id, PolicyParams]  per-site DE-optimal parameters
    theta_vector: np.ndarray [num_sites * PARAM_DIM]  flat concatenated θ*
    objective_value: float  E[total_cost] at θ* (lower = better)
    de_converged: bool  whether DE solved the problem satisfactorily
    """
    sample_id: str
    network: SoPNetwork
    node_features: np.ndarray    # [num_sites, 14]
    edge_features: np.ndarray    # [num_lanes, 4]
    edge_index: np.ndarray       # [2, num_lanes]
    optimal_theta: Dict[str, PolicyParams]
    theta_vector: np.ndarray     # [num_sites * PARAM_DIM]
    objective_value: float
    de_converged: bool

    NODE_FEATURE_DIM: int = 14
    EDGE_FEATURE_DIM: int = 4


# ---------------------------------------------------------------------------
# Oracle
# ---------------------------------------------------------------------------

class SoPGraphSAGEOracle:
    """
    CFA/DE oracle for S&OP GraphSAGE training data generation.

    For each synthetic network, runs Differential Evolution to find θ*,
    then packages (graph_features, θ*) as a supervised training sample.
    The GraphSAGE is trained to predict θ* from graph features alone.
    """

    def __init__(
        self,
        seed: Optional[int] = None,
        num_mc_scenarios: int = 30,
        de_max_iter: int = 100,
        de_popsize: int = 10,
        de_tol: float = 0.01,
    ) -> None:
        """
        Args:
            seed: Random seed for reproducibility.
            num_mc_scenarios: Monte Carlo scenarios per DE objective evaluation.
                              Higher = more accurate labels but slower.
            de_max_iter: Maximum DE iterations per network.
            de_popsize: DE population size multiplier.
            de_tol: DE convergence tolerance.
        """
        if not SCIPY_AVAILABLE:
            raise ImportError(
                "scipy is required for SoPGraphSAGEOracle. "
                "Install with: pip install scipy"
            )
        self.rng = np.random.default_rng(seed)
        self.num_mc_scenarios = num_mc_scenarios
        self.de_max_iter = de_max_iter
        self.de_popsize = de_popsize
        self.de_tol = de_tol

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_samples(
        self,
        num_scenarios: int = 100,
        num_sites_range: Tuple[int, int] = (4, 12),
        planning_horizon_weeks: int = 26,
        phases: Tuple[int, ...] = (1, 2, 3),
    ) -> List[SoPTrainingSample]:
        """
        Generate num_scenarios DE-labeled GraphSAGE training samples.

        WARNING: Each sample requires ~30-120s of DE optimization.
        For production-scale generation, parallelise with multiprocessing:

            from multiprocessing import Pool
            with Pool(processes=8) as pool:
                samples = pool.starmap(oracle.generate_samples, [(10,)] * 10)

        phases controls network complexity:
          1 = simple linear topology, stable demand
          2 = branching network, seasonal demand
          3 = complex DAG, high variability, multi-sourcing
        """
        samples: List[SoPTrainingSample] = []
        per_phase = max(1, num_scenarios // len(phases))

        for phase in phases:
            n_actual = per_phase if phase < len(phases) else num_scenarios - len(samples)
            for i in range(n_actual):
                num_sites = int(self.rng.integers(
                    num_sites_range[0],
                    num_sites_range[1] + 1,
                ))
                network = self._sample_network(num_sites, phase, planning_horizon_weeks)
                sample = self._solve(network)
                samples.append(sample)
                logger.debug(
                    "SoPOracle sample %d/%d: sites=%d, objective=%.2f, converged=%s",
                    len(samples), num_scenarios,
                    len(network.sites), sample.objective_value, sample.de_converged,
                )

        logger.info(
            "SoPGraphSAGEOracle generated %d samples, %.1f%% DE-converged",
            len(samples),
            100.0 * sum(s.de_converged for s in samples) / max(len(samples), 1),
        )
        return samples

    # ------------------------------------------------------------------
    # DE solver
    # ------------------------------------------------------------------

    def _solve(self, network: SoPNetwork) -> SoPTrainingSample:
        """Run Differential Evolution to find θ* for this network."""
        S = len(network.sites)
        param_dim = PolicyParams.PARAM_DIM

        # θ vector = [site_0_params, site_1_params, ..., site_{S-1}_params]
        # Each site contributes PARAM_DIM parameters
        all_bounds = POLICY_BOUNDS * S   # S sites × PARAM_DIM bounds each

        mc_seed = int(self.rng.integers(0, 2**31))

        def objective(theta_flat: np.ndarray) -> float:
            return self._mc_objective(theta_flat, network, mc_seed)

        result: OptimizeResult = differential_evolution(
            objective,
            bounds=all_bounds,
            seed=mc_seed,
            maxiter=self.de_max_iter,
            popsize=self.de_popsize,
            tol=self.de_tol,
            workers=1,           # Single-threaded within each oracle call
            updating="deferred",
        )

        theta_flat = result.x
        converged = result.success or (result.fun < 1e8)

        # Unpack θ per site
        optimal_theta: Dict[str, PolicyParams] = {}
        for i, site in enumerate(network.sites):
            start = i * param_dim
            optimal_theta[site.site_id] = PolicyParams.from_vector(
                theta_flat[start: start + param_dim]
            )

        node_features, edge_features, edge_index = self._build_graph_features(network)

        return SoPTrainingSample(
            sample_id=str(uuid.uuid4()),
            network=network,
            node_features=node_features,
            edge_features=edge_features,
            edge_index=edge_index,
            optimal_theta=optimal_theta,
            theta_vector=theta_flat.astype(np.float32),
            objective_value=float(result.fun),
            de_converged=converged,
        )

    def _mc_objective(
        self,
        theta_flat: np.ndarray,
        network: SoPNetwork,
        seed: int,
    ) -> float:
        """
        Monte Carlo estimate of expected total cost under policy θ.

        Evaluates the policy over num_mc_scenarios random demand/lead-time
        realizations and returns the mean total cost.

        Total cost = Σ_sites [ holding_cost + stockout_cost + ordering_cost ]
        """
        rng = np.random.default_rng(seed)
        param_dim = PolicyParams.PARAM_DIM
        total_cost = 0.0

        for _ in range(self.num_mc_scenarios):
            scenario_cost = 0.0

            for i, site in enumerate(network.sites):
                params = PolicyParams.from_vector(
                    theta_flat[i * param_dim: (i + 1) * param_dim]
                )

                # Simulate demand and inventory over planning horizon
                ss_qty = (
                    params.safety_stock_multiplier
                    * site.avg_weekly_demand
                    * site.demand_variability_cv
                    * np.sqrt(site.avg_lead_time_weeks)
                )
                order_up_to = params.order_up_to_days / 7.0 * site.avg_weekly_demand

                # Simulate weekly inventory positions
                inventory = site.on_hand_qty
                for week in range(network.planning_horizon_weeks):
                    # Realise demand
                    demand = float(max(0.0, rng.normal(
                        site.avg_weekly_demand,
                        site.avg_weekly_demand * site.demand_variability_cv,
                    )))

                    # Realise supply (lead time jitter)
                    lead_time = float(max(0.5, rng.normal(
                        site.avg_lead_time_weeks,
                        site.avg_lead_time_weeks * site.lead_time_variability_cv,
                    )))

                    # Replenishment decision at reorder point
                    reorder_point = params.reorder_point_days / 7.0 * site.avg_weekly_demand
                    if inventory <= reorder_point:
                        order_qty = max(0.0, order_up_to + ss_qty - inventory)
                        # Ordering cost
                        if order_qty > 0:
                            scenario_cost += site.ordering_cost
                        # Supply arrives after lead time (simplified: immediate for small LTs)
                        if lead_time <= 1.0:
                            inventory += order_qty

                    # Fulfil demand
                    fulfilled = min(inventory, demand)
                    shortfall = demand - fulfilled
                    inventory = max(0.0, inventory - demand)

                    # Holding cost on average inventory
                    scenario_cost += inventory * site.unit_cost * site.annual_holding_rate / 52.0

                    # Stockout cost
                    scenario_cost += shortfall * site.stockout_cost_per_unit

                # Penalty for poor service level (soft constraint)
                target_sl = params.service_level_target
                implied_sl = 1.0 - min(0.5, ss_qty / max(site.avg_weekly_demand * site.avg_lead_time_weeks, 1e-6))
                if implied_sl < target_sl:
                    scenario_cost += (target_sl - implied_sl) * site.stockout_cost_per_unit * site.avg_weekly_demand * 52.0

            total_cost += scenario_cost

        return total_cost / self.num_mc_scenarios

    # ------------------------------------------------------------------
    # Feature construction
    # ------------------------------------------------------------------

    def _build_graph_features(
        self,
        network: SoPNetwork,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Build [num_sites, 14] node features, [num_lanes, 4] edge features,
        and [2, num_lanes] edge index for the GraphSAGE.

        Node features [14]:
          0: avg_weekly_demand (normalised)
          1: demand_variability_cv
          2: avg_lead_time_weeks (normalised)
          3: lead_time_variability_cv
          4: on_hand_qty (normalised)
          5: unit_cost (normalised)
          6: annual_holding_rate
          7: stockout_cost_per_unit (normalised)
          8: ordering_cost (normalised)
          9: criticality_score
         10: is_supply_node
         11: is_demand_node
         12: is_manufacturer
         13: is_inventory_node

        Edge features [4]:
          0: lead_time_weeks (normalised)
          1: transport_cost_per_unit (normalised)
          2: reliability
          3: capacity_units_per_week (normalised)
        """
        S = len(network.sites)
        L = len(network.lanes)

        site_idx: Dict[str, int] = {s.site_id: i for i, s in enumerate(network.sites)}

        # Normalisation anchors
        max_demand   = max((s.avg_weekly_demand for s in network.sites), default=1.0) or 1.0
        max_lt       = max((s.avg_lead_time_weeks for s in network.sites), default=1.0) or 1.0
        max_oh       = max((s.on_hand_qty for s in network.sites), default=1.0) or 1.0
        max_cost     = max((s.unit_cost for s in network.sites), default=1.0) or 1.0
        max_stockout = max((s.stockout_cost_per_unit for s in network.sites), default=1.0) or 1.0
        max_order_c  = max((s.ordering_cost for s in network.sites), default=1.0) or 1.0
        max_lane_lt  = max((la.lead_time_weeks for la in network.lanes), default=1.0) or 1.0
        max_lane_tc  = max((la.transport_cost_per_unit for la in network.lanes), default=1.0) or 1.0
        max_lane_cap = max((la.capacity_units_per_week for la in network.lanes), default=1.0) or 1.0

        node_features = np.zeros((S, SoPTrainingSample.NODE_FEATURE_DIM), dtype=np.float32)
        for i, site in enumerate(network.sites):
            node_features[i] = [
                site.avg_weekly_demand / max_demand,
                site.demand_variability_cv,
                site.avg_lead_time_weeks / max_lt,
                site.lead_time_variability_cv,
                site.on_hand_qty / max_oh,
                site.unit_cost / max_cost,
                site.annual_holding_rate,
                site.stockout_cost_per_unit / max_stockout,
                site.ordering_cost / max_order_c,
                site.criticality_score,
                float(site.master_type == "MARKET_SUPPLY"),
                float(site.master_type == "MARKET_DEMAND"),
                float(site.master_type == "MANUFACTURER"),
                float(site.master_type == "INVENTORY"),
            ]

        edge_features = np.zeros((L, SoPTrainingSample.EDGE_FEATURE_DIM), dtype=np.float32)
        edge_index = np.zeros((2, L), dtype=np.int64)
        for l_idx, lane in enumerate(network.lanes):
            from_i = site_idx.get(lane.from_site, 0)
            to_i   = site_idx.get(lane.to_site, 0)
            edge_index[:, l_idx] = [from_i, to_i]
            edge_features[l_idx] = [
                lane.lead_time_weeks / max_lane_lt,
                lane.transport_cost_per_unit / max_lane_tc,
                lane.reliability,
                lane.capacity_units_per_week / max_lane_cap,
            ]

        return node_features, edge_features, edge_index

    # ------------------------------------------------------------------
    # Network sampling
    # ------------------------------------------------------------------

    def _sample_network(
        self,
        num_sites: int,
        phase: int,
        planning_horizon_weeks: int,
    ) -> SoPNetwork:
        """Generate a random supply chain network for the given complexity phase."""
        rng = self.rng
        variance = {1: 0.15, 2: 0.40, 3: 0.75}[phase]

        def jitter(v: float, pct: float = variance) -> float:
            return float(max(0.0, v * (1.0 + rng.uniform(-pct, pct))))

        # Assign site types
        n_supply = max(1, num_sites // 5)
        n_demand = max(1, num_sites // 4)
        n_mfg    = 1 if phase >= 2 and num_sites >= 5 else 0
        n_inv    = max(0, num_sites - n_supply - n_demand - n_mfg)

        types = (
            ["MARKET_SUPPLY"] * n_supply
            + ["MANUFACTURER"] * n_mfg
            + ["INVENTORY"] * n_inv
            + ["MARKET_DEMAND"] * n_demand
        )
        while len(types) < num_sites:
            types.append("INVENTORY")
        types = types[:num_sites]

        sites: List[SoPNetworkSite] = []
        for i, mtype in enumerate(types):
            is_demand = mtype == "MARKET_DEMAND"
            sites.append(SoPNetworkSite(
                site_id=f"NET_{i:02d}",
                master_type=mtype,
                avg_weekly_demand=jitter(200.0) if is_demand else 0.0,
                demand_variability_cv=float(rng.uniform(0.05, variance * 1.5)),
                avg_lead_time_weeks=jitter(2.0) if mtype != "MARKET_DEMAND" else 0.0,
                lead_time_variability_cv=float(rng.uniform(0.05, variance)),
                on_hand_qty=jitter(800.0),
                unit_cost=float(rng.uniform(5.0, 200.0)),
                annual_holding_rate=float(rng.uniform(0.15, 0.35)),
                stockout_cost_per_unit=float(rng.uniform(10.0, 100.0)),
                ordering_cost=float(rng.uniform(50.0, 500.0)),
                criticality_score=float(rng.uniform(0.2, 1.0)),
            ))

        supply_ids = [s.site_id for s in sites if s.master_type in ("MARKET_SUPPLY", "MANUFACTURER")]
        inv_ids    = [s.site_id for s in sites if s.master_type == "INVENTORY"]
        demand_ids = [s.site_id for s in sites if s.master_type == "MARKET_DEMAND"]

        lanes: List[SoPNetworkLane] = []

        def make_lane(from_id: str, to_id: str) -> SoPNetworkLane:
            return SoPNetworkLane(
                from_site=from_id,
                to_site=to_id,
                lead_time_weeks=jitter(2.0),
                transport_cost_per_unit=float(rng.uniform(0.5, 20.0)),
                reliability=float(rng.uniform(0.7 + 0.2 * (1 - variance), 0.99)),
                capacity_units_per_week=jitter(1000.0),
            )

        # Supply → Inventory
        middle = inv_ids if inv_ids else demand_ids
        for src in supply_ids:
            for dst in (middle[:2] if phase == 1 else middle[:4]):
                lanes.append(make_lane(src, dst))

        # Inventory → Demand
        for src in inv_ids:
            for dst in demand_ids:
                lanes.append(make_lane(src, dst))

        # Phase 3: cross-links + multi-sourcing
        if phase == 3:
            for j in range(min(len(supply_ids), 2)):
                for dst in demand_ids[:2]:
                    lanes.append(make_lane(supply_ids[j], dst))

        return SoPNetwork(
            network_id=str(uuid.uuid4()),
            sites=sites,
            lanes=lanes,
            planning_horizon_weeks=planning_horizon_weeks,
        )


# ---------------------------------------------------------------------------
# GraphSAGE Trainer stub (supervised training on oracle samples)
# ---------------------------------------------------------------------------

class SoPGraphSAGETrainer:
    """
    Trains the S&OP GraphSAGE to predict θ* from network graph features.

    Uses the samples generated by SoPGraphSAGEOracle as (X, y) pairs:
      X = (node_features, edge_features, edge_index)  ← graph structure
      y = theta_vector                                 ← DE-optimal parameters

    Loss = MSE(predicted_theta, oracle_theta)  per policy parameter
    Additionally tracks: parameter-wise MAE, convergence curve.

    Integration: After training, call predict_theta(network) which runs the
    GraphSAGE forward pass and returns the predicted θ for each site.
    This replaces the weekly DE run with a ~1ms neural network inference.

    NOTE: Full integration with the existing ScalableGraphSAGE model in
    backend/app/models/gnn/scalable_graphsage.py is pending. This trainer
    currently uses a lightweight MLP-on-node-features as a stand-in;
    replace _build_model() with the full GraphSAGE for production use.
    """

    def __init__(
        self,
        samples: List[SoPTrainingSample],
        node_feature_dim: int = SoPTrainingSample.NODE_FEATURE_DIM,
        hidden_dim: int = 128,
        num_layers: int = 3,
        learning_rate: float = 1e-3,
    ) -> None:
        try:
            import torch
            import torch.nn as nn
            self.torch = torch
            self.nn = nn
            self._torch_available = True
        except ImportError:
            logger.warning("PyTorch not available — training disabled")
            self._torch_available = False

        self.samples = [s for s in samples if s.de_converged]
        logger.info(
            "SoPGraphSAGETrainer: %d/%d converged samples available for training",
            len(self.samples), len(samples),
        )
        self.node_feature_dim = node_feature_dim
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.lr = learning_rate
        self.model = None

    def train(
        self,
        epochs: int = 50,
        batch_size: int = 16,
        val_split: float = 0.1,
    ) -> Dict[str, Any]:
        """
        Train GraphSAGE on oracle samples.
        Returns training metrics dict: {train_loss, val_loss, epoch_losses}.
        """
        if not self._torch_available:
            return {"error": "PyTorch not available"}
        if len(self.samples) < 2:
            return {"error": "insufficient converged samples for training"}

        torch = self.torch
        nn = self.nn

        # Determine output dimension from first sample
        theta_dim = self.samples[0].theta_vector.shape[0]
        self.model = self._build_model(self.node_feature_dim, self.hidden_dim, theta_dim)
        optimizer = torch.optim.Adam(self.model.parameters(), lr=self.lr)
        loss_fn = nn.MSELoss()

        # Train/val split
        split_idx = max(1, int(len(self.samples) * (1 - val_split)))
        train_samples = self.samples[:split_idx]
        val_samples   = self.samples[split_idx:]

        epoch_losses: List[float] = []
        for epoch in range(epochs):
            self.model.train()
            epoch_loss = 0.0
            idx = list(range(len(train_samples)))
            np.random.shuffle(idx)

            for start in range(0, len(idx), batch_size):
                batch_idx = idx[start: start + batch_size]
                X_batch = torch.stack([
                    torch.tensor(train_samples[i].node_features.mean(axis=0), dtype=torch.float32)
                    for i in batch_idx
                ])
                y_batch = torch.stack([
                    torch.tensor(train_samples[i].theta_vector, dtype=torch.float32)
                    for i in batch_idx
                ])

                optimizer.zero_grad()
                y_pred = self.model(X_batch)
                loss = loss_fn(y_pred, y_batch)
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()

            avg_loss = epoch_loss / max(len(train_samples) // batch_size, 1)
            epoch_losses.append(avg_loss)
            if epoch % 10 == 0:
                logger.debug("SoPGraphSAGETrainer epoch %d/%d loss=%.4f", epoch + 1, epochs, avg_loss)

        # Validation loss
        self.model.eval()
        val_loss = 0.0
        if val_samples:
            with torch.no_grad():
                X_val = torch.stack([
                    torch.tensor(s.node_features.mean(axis=0), dtype=torch.float32)
                    for s in val_samples
                ])
                y_val = torch.stack([
                    torch.tensor(s.theta_vector, dtype=torch.float32)
                    for s in val_samples
                ])
                val_loss = float(loss_fn(self.model(X_val), y_val).item())

        return {
            "train_loss": epoch_losses[-1] if epoch_losses else None,
            "val_loss": val_loss,
            "epoch_losses": epoch_losses,
            "num_train_samples": len(train_samples),
            "num_val_samples": len(val_samples),
            "theta_dim": theta_dim,
        }

    def predict_theta(self, network: SoPNetwork) -> Dict[str, PolicyParams]:
        """
        Predict optimal policy parameters for a new network in ~1ms.
        Replaces weekly DE optimization at inference time.
        """
        if self.model is None:
            raise RuntimeError("Model not trained — call train() first")

        torch = self.torch
        S = len(network.sites)
        feat_oracle = SoPGraphSAGEOracle.__new__(SoPGraphSAGEOracle)
        feat_oracle.rng = np.random.default_rng(0)
        node_features, _, _ = feat_oracle._build_graph_features(network)

        x = torch.tensor(node_features.mean(axis=0), dtype=torch.float32).unsqueeze(0)
        with torch.no_grad():
            theta_pred = self.model(x).squeeze(0).numpy()

        param_dim = PolicyParams.PARAM_DIM
        result: Dict[str, PolicyParams] = {}
        for i, site in enumerate(network.sites):
            start = i * param_dim
            result[site.site_id] = PolicyParams.from_vector(
                theta_pred[start: start + param_dim]
            )
        return result

    def _build_model(self, input_dim: int, hidden_dim: int, output_dim: int):
        """Build a lightweight MLP as a stand-in for the full GraphSAGE."""
        nn = self.nn
        layers = [nn.Linear(input_dim, hidden_dim), nn.ReLU(), nn.Dropout(0.1)]
        for _ in range(self.num_layers - 2):
            layers += [nn.Linear(hidden_dim, hidden_dim), nn.ReLU(), nn.Dropout(0.1)]
        layers.append(nn.Linear(hidden_dim, output_dim))
        return nn.Sequential(*layers)
