/**
 * S&OP Policy Envelope Page
 *
 * Three-tab interface for the S&OP Policy Envelope:
 *   1. Input/Review  - Enter (INPUT mode) or review (ACTIVE mode) Policy Envelope parameters
 *   2. Feed-back     - FeedbackSignalCards for signals targeted to "sop"
 *   3. Lineage       - ArtifactLineage for the current Policy Envelope
 *
 * In INPUT mode the user supplies policy parameters manually.
 * In ACTIVE mode values are pre-filled from the active envelope generated by
 * Autonomy Simulation, and changed values are highlighted with an amber background.
 */

import React, { useState, useEffect } from 'react';
import {
  Box,
  Paper,
  Typography,
  Grid,
  Tabs,
  Tab,
  Button,
  TextField,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Alert,
  Chip,
  IconButton,
  Divider,
  CircularProgress,
} from '@mui/material';
import {
  Add as AddIcon,
  Save as SaveIcon,
  Delete as DeleteIcon,
} from '@mui/icons-material';

import LayerModeIndicator from '../../components/cascade/LayerModeIndicator';
import ArtifactLineage from '../../components/cascade/ArtifactLineage';
import FeedbackSignalCards from '../../components/cascade/FeedbackSignalCards';
import {
  getLayerLicenses,
  getActivePolicyEnvelope,
  createPolicyEnvelope,
} from '../../services/planningCascadeApi';
import { api } from '../../services/api';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const DEFAULT_SERVICE_TIER = { segment: '', otif_floor: 95, fill_rate_target: 98 };
const DEFAULT_CATEGORY_POLICY = { category: '', safety_stock_wos: 2.0, dos_ceiling: 21, expedite_cap: 10000 };

/**
 * Returns an sx prop that applies an amber highlight when a value has been
 * changed relative to its original (server-supplied) counterpart.
 */
const changedSx = (current, original) => {
  if (original === undefined || original === null) return {};
  if (String(current) !== String(original)) {
    return { bgcolor: 'rgba(255, 183, 77, 0.25)' };
  }
  return {};
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

const SOPPolicyPage = ({ configId, groupId }) => {
  // -- UI state
  const [activeTab, setActiveTab] = useState(0);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState(null);
  const [saveSuccess, setSaveSuccess] = useState(false);

  // -- Layer mode
  const [layerMode, setLayerMode] = useState(null); // "active" | "input" | "disabled"

  // -- Policy Envelope loaded from the server (used for diff highlighting)
  const [currentEnvelopeId, setCurrentEnvelopeId] = useState(null);
  const [originalServiceTiers, setOriginalServiceTiers] = useState([]);
  const [originalCategoryPolicies, setOriginalCategoryPolicies] = useState([]);
  const [originalTotalInventoryCap, setOriginalTotalInventoryCap] = useState('');
  const [originalGmroiTarget, setOriginalGmroiTarget] = useState('');

  // -- Editable form state
  const [serviceTiers, setServiceTiers] = useState([
    { segment: 'strategic', otif_floor: 99, fill_rate_target: 99 },
    { segment: 'standard', otif_floor: 95, fill_rate_target: 98 },
    { segment: 'transactional', otif_floor: 90, fill_rate_target: 95 },
  ]);
  const [categoryPolicies, setCategoryPolicies] = useState([
    { category: 'frozen_proteins', safety_stock_wos: 2.0, dos_ceiling: 21, expedite_cap: 15000 },
    { category: 'refrigerated_dairy', safety_stock_wos: 1.5, dos_ceiling: 14, expedite_cap: 10000 },
    { category: 'dry_pantry', safety_stock_wos: 3.0, dos_ceiling: 45, expedite_cap: 5000 },
  ]);
  const [totalInventoryCap, setTotalInventoryCap] = useState('2500000');
  const [gmroiTarget, setGmroiTarget] = useState('3.0');

  const isActive = layerMode === 'active';

  // -----------------------------------------------------------------------
  // Data loading
  // -----------------------------------------------------------------------

  useEffect(() => {
    loadAll();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [configId, groupId]);

  const loadAll = async () => {
    setLoading(true);
    try {
      await Promise.all([loadLayerMode(), loadEnvelope()]);
    } finally {
      setLoading(false);
    }
  };

  const loadLayerMode = async () => {
    try {
      const data = await getLayerLicenses(groupId);
      const sopMode = data?.layers?.sop?.mode || 'input';
      setLayerMode(sopMode);
    } catch (err) {
      console.error('Failed to load layer licenses', err);
      setLayerMode('input');
    }
  };

  const loadEnvelope = async () => {
    try {
      const data = await getActivePolicyEnvelope(configId);
      if (data) {
        setCurrentEnvelopeId(data.id);
        applyEnvelopeToForm(data);
      }
    } catch (err) {
      // No active envelope yet -- keep defaults
      console.log('No active policy envelope found');
    }
  };

  /**
   * Maps the server response into form state and stores copies for
   * change-highlighting in ACTIVE mode.
   */
  const applyEnvelopeToForm = (envelope) => {
    // -- Service tiers
    if (envelope.service_tiers && envelope.service_tiers.length > 0) {
      const tiers = envelope.service_tiers.map((t) => ({
        segment: t.segment || '',
        otif_floor: t.otif_floor != null ? t.otif_floor : 95,
        fill_rate_target: t.fill_rate_target != null ? t.fill_rate_target : 98,
      }));
      setServiceTiers(tiers);
      setOriginalServiceTiers(JSON.parse(JSON.stringify(tiers)));
    } else if (envelope.otif_floors) {
      // Fallback: legacy flat-map format
      const tiers = Object.entries(envelope.otif_floors).map(([segment, floor]) => ({
        segment,
        otif_floor: typeof floor === 'number' && floor <= 1 ? floor * 100 : floor,
        fill_rate_target: 98,
      }));
      setServiceTiers(tiers);
      setOriginalServiceTiers(JSON.parse(JSON.stringify(tiers)));
    }

    // -- Category policies
    if (envelope.category_policies && envelope.category_policies.length > 0) {
      const policies = envelope.category_policies.map((p) => ({
        category: p.category || '',
        safety_stock_wos: p.safety_stock_wos != null ? p.safety_stock_wos : 2.0,
        dos_ceiling: p.dos_ceiling != null ? p.dos_ceiling : 21,
        expedite_cap: p.expedite_cap != null ? p.expedite_cap : 10000,
      }));
      setCategoryPolicies(policies);
      setOriginalCategoryPolicies(JSON.parse(JSON.stringify(policies)));
    } else if (envelope.safety_stock_targets) {
      const policies = Object.entries(envelope.safety_stock_targets).map(([category, wos]) => ({
        category,
        safety_stock_wos: wos,
        dos_ceiling: envelope.dos_ceilings?.[category] || 21,
        expedite_cap: envelope.expedite_caps?.[category] || 10000,
      }));
      setCategoryPolicies(policies);
      setOriginalCategoryPolicies(JSON.parse(JSON.stringify(policies)));
    }

    // -- Financial guardrails
    if (envelope.total_inventory_cap != null) {
      setTotalInventoryCap(String(envelope.total_inventory_cap));
      setOriginalTotalInventoryCap(String(envelope.total_inventory_cap));
    }
    if (envelope.gmroi_target != null) {
      setGmroiTarget(String(envelope.gmroi_target));
      setOriginalGmroiTarget(String(envelope.gmroi_target));
    }
  };

  // -----------------------------------------------------------------------
  // Table row helpers
  // -----------------------------------------------------------------------

  const updateServiceTier = (index, field, value) => {
    setServiceTiers((prev) => {
      const updated = [...prev];
      updated[index] = {
        ...updated[index],
        [field]: field === 'segment' ? value : parseFloat(value) || 0,
      };
      return updated;
    });
  };

  const addServiceTier = () => {
    setServiceTiers((prev) => [...prev, { ...DEFAULT_SERVICE_TIER }]);
  };

  const removeServiceTier = (index) => {
    setServiceTiers((prev) => prev.filter((_, i) => i !== index));
  };

  const updateCategoryPolicy = (index, field, value) => {
    setCategoryPolicies((prev) => {
      const updated = [...prev];
      updated[index] = {
        ...updated[index],
        [field]: field === 'category' ? value : parseFloat(value) || 0,
      };
      return updated;
    });
  };

  const addCategoryPolicy = () => {
    setCategoryPolicies((prev) => [...prev, { ...DEFAULT_CATEGORY_POLICY }]);
  };

  const removeCategoryPolicy = (index) => {
    setCategoryPolicies((prev) => prev.filter((_, i) => i !== index));
  };

  // -----------------------------------------------------------------------
  // Save
  // -----------------------------------------------------------------------

  const handleSave = async () => {
    setSaving(true);
    setSaveError(null);
    setSaveSuccess(false);
    try {
      const payload = {
        config_id: configId,
        group_id: groupId,
        mode: layerMode === 'active' ? 'ACTIVE' : 'INPUT',
        service_tiers: serviceTiers,
        category_policies: categoryPolicies,
        total_inventory_cap: parseFloat(totalInventoryCap) || 0,
        gmroi_target: parseFloat(gmroiTarget) || 0,
      };
      const result = await createPolicyEnvelope(payload);
      if (result?.id) {
        setCurrentEnvelopeId(result.id);
      }
      // Refresh originals so amber highlights reset
      setOriginalServiceTiers(JSON.parse(JSON.stringify(serviceTiers)));
      setOriginalCategoryPolicies(JSON.parse(JSON.stringify(categoryPolicies)));
      setOriginalTotalInventoryCap(totalInventoryCap);
      setOriginalGmroiTarget(gmroiTarget);
      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 4000);
    } catch (err) {
      console.error('Failed to save policy envelope', err);
      setSaveError(err?.response?.data?.detail || 'Failed to save policy envelope. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  // -----------------------------------------------------------------------
  // Change detection helpers (for ACTIVE mode amber highlighting)
  // -----------------------------------------------------------------------

  const tierChanged = (index, field) => {
    if (!isActive) return {};
    const orig = originalServiceTiers[index];
    if (!orig) return {};
    return changedSx(serviceTiers[index]?.[field], orig[field]);
  };

  const policyChanged = (index, field) => {
    if (!isActive) return {};
    const orig = originalCategoryPolicies[index];
    if (!orig) return {};
    return changedSx(categoryPolicies[index]?.[field], orig[field]);
  };

  // -----------------------------------------------------------------------
  // Render: Tab 1 -- Input / Review
  // -----------------------------------------------------------------------

  const renderInputReviewTab = () => (
    <Box>
      {/* Layer Mode Indicator */}
      <Box mb={3}>
        <LayerModeIndicator layer="sop" mode={layerMode || 'input'} />
      </Box>

      {/* Mode banners */}
      {isActive && (
        <Box mb={2}>
          <Chip
            label="Generated by: Autonomy Simulation"
            color="success"
            variant="outlined"
            size="small"
            sx={{ mb: 1 }}
          />
          <Alert severity="success" variant="outlined" sx={{ mb: 2 }}>
            These values were generated by the Autonomy S&OP simulation layer. You may review
            and adjust any value. Changed fields are highlighted in amber.
          </Alert>
        </Box>
      )}

      {!isActive && (
        <Alert severity="info" sx={{ mb: 3 }}>
          <Typography variant="body2">
            Manual entry mode. Enter your S&OP policy parameters below. The Supply and
            Allocation Agents will enforce these constraints during execution.
          </Typography>
        </Alert>
      )}

      {/* Service Tier Table */}
      <Paper variant="outlined" sx={{ p: 2, mb: 3 }}>
        <Box display="flex" justifyContent="space-between" alignItems="center" mb={1}>
          <Typography variant="subtitle1">Service Tier Targets</Typography>
          <Button size="small" startIcon={<AddIcon />} onClick={addServiceTier}>
            Add Row
          </Button>
        </Box>
        <Divider sx={{ mb: 1 }} />
        <TableContainer>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>Segment</TableCell>
                <TableCell>OTIF Floor %</TableCell>
                <TableCell>Fill Rate Target %</TableCell>
                <TableCell width={48} />
              </TableRow>
            </TableHead>
            <TableBody>
              {serviceTiers.map((tier, index) => (
                <TableRow key={index}>
                  <TableCell sx={tierChanged(index, 'segment')}>
                    <TextField
                      size="small"
                      variant="standard"
                      value={tier.segment}
                      onChange={(e) => updateServiceTier(index, 'segment', e.target.value)}
                      placeholder="e.g. strategic"
                      fullWidth
                    />
                  </TableCell>
                  <TableCell sx={tierChanged(index, 'otif_floor')}>
                    <TextField
                      size="small"
                      variant="standard"
                      type="number"
                      value={tier.otif_floor}
                      onChange={(e) => updateServiceTier(index, 'otif_floor', e.target.value)}
                      inputProps={{ min: 0, max: 100, step: 1 }}
                      sx={{ width: 80 }}
                    />
                  </TableCell>
                  <TableCell sx={tierChanged(index, 'fill_rate_target')}>
                    <TextField
                      size="small"
                      variant="standard"
                      type="number"
                      value={tier.fill_rate_target}
                      onChange={(e) => updateServiceTier(index, 'fill_rate_target', e.target.value)}
                      inputProps={{ min: 0, max: 100, step: 1 }}
                      sx={{ width: 80 }}
                    />
                  </TableCell>
                  <TableCell>
                    <IconButton size="small" onClick={() => removeServiceTier(index)}>
                      <DeleteIcon fontSize="small" />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))}
              {serviceTiers.length === 0 && (
                <TableRow>
                  <TableCell colSpan={4} align="center">
                    <Typography variant="body2" color="text.secondary">
                      No service tiers defined. Click "Add Row" to begin.
                    </Typography>
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>

      {/* Category Policy Table */}
      <Paper variant="outlined" sx={{ p: 2, mb: 3 }}>
        <Box display="flex" justifyContent="space-between" alignItems="center" mb={1}>
          <Typography variant="subtitle1">Category Policies</Typography>
          <Button size="small" startIcon={<AddIcon />} onClick={addCategoryPolicy}>
            Add Row
          </Button>
        </Box>
        <Divider sx={{ mb: 1 }} />
        <TableContainer>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>Category</TableCell>
                <TableCell>Safety Stock (WOS)</TableCell>
                <TableCell>DOS Ceiling (days)</TableCell>
                <TableCell>Expedite Cap ($)</TableCell>
                <TableCell width={48} />
              </TableRow>
            </TableHead>
            <TableBody>
              {categoryPolicies.map((policy, index) => (
                <TableRow key={index}>
                  <TableCell sx={policyChanged(index, 'category')}>
                    <TextField
                      size="small"
                      variant="standard"
                      value={policy.category}
                      onChange={(e) => updateCategoryPolicy(index, 'category', e.target.value)}
                      placeholder="e.g. frozen_proteins"
                      fullWidth
                    />
                  </TableCell>
                  <TableCell sx={policyChanged(index, 'safety_stock_wos')}>
                    <TextField
                      size="small"
                      variant="standard"
                      type="number"
                      value={policy.safety_stock_wos}
                      onChange={(e) => updateCategoryPolicy(index, 'safety_stock_wos', e.target.value)}
                      inputProps={{ min: 0, step: 0.5 }}
                      sx={{ width: 80 }}
                    />
                  </TableCell>
                  <TableCell sx={policyChanged(index, 'dos_ceiling')}>
                    <TextField
                      size="small"
                      variant="standard"
                      type="number"
                      value={policy.dos_ceiling}
                      onChange={(e) => updateCategoryPolicy(index, 'dos_ceiling', e.target.value)}
                      inputProps={{ min: 1 }}
                      sx={{ width: 80 }}
                    />
                  </TableCell>
                  <TableCell sx={policyChanged(index, 'expedite_cap')}>
                    <TextField
                      size="small"
                      variant="standard"
                      type="number"
                      value={policy.expedite_cap}
                      onChange={(e) => updateCategoryPolicy(index, 'expedite_cap', e.target.value)}
                      inputProps={{ min: 0, step: 1000 }}
                      sx={{ width: 100 }}
                    />
                  </TableCell>
                  <TableCell>
                    <IconButton size="small" onClick={() => removeCategoryPolicy(index)}>
                      <DeleteIcon fontSize="small" />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))}
              {categoryPolicies.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} align="center">
                    <Typography variant="body2" color="text.secondary">
                      No category policies defined. Click "Add Row" to begin.
                    </Typography>
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>

      {/* Financial Guardrails */}
      <Paper variant="outlined" sx={{ p: 2, mb: 3 }}>
        <Typography variant="subtitle1" gutterBottom>
          Financial Guardrails
        </Typography>
        <Divider sx={{ mb: 2 }} />
        <Grid container spacing={3}>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Total Inventory Cap ($)"
              type="number"
              value={totalInventoryCap}
              onChange={(e) => setTotalInventoryCap(e.target.value)}
              InputProps={{ startAdornment: <Typography sx={{ mr: 0.5 }}>$</Typography> }}
              sx={isActive ? changedSx(totalInventoryCap, originalTotalInventoryCap) : {}}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="GMROI Target"
              type="number"
              value={gmroiTarget}
              onChange={(e) => setGmroiTarget(e.target.value)}
              inputProps={{ step: 0.1 }}
              sx={isActive ? changedSx(gmroiTarget, originalGmroiTarget) : {}}
            />
          </Grid>
        </Grid>
      </Paper>

      {/* Save feedback */}
      {saveError && (
        <Alert severity="error" sx={{ mb: 2 }} onClose={() => setSaveError(null)}>
          {saveError}
        </Alert>
      )}
      {saveSuccess && (
        <Alert severity="success" sx={{ mb: 2 }}>
          Policy Envelope saved successfully.
        </Alert>
      )}

      {/* Save button */}
      <Box display="flex" justifyContent="flex-end">
        <Button
          variant="contained"
          startIcon={saving ? <CircularProgress size={18} color="inherit" /> : <SaveIcon />}
          onClick={handleSave}
          disabled={saving}
        >
          {saving ? 'Saving...' : 'Save Policy Envelope'}
        </Button>
      </Box>
    </Box>
  );

  // -----------------------------------------------------------------------
  // Render: Tab 2 -- Feed-back
  // -----------------------------------------------------------------------

  const renderFeedbackTab = () => (
    <Box>
      <Typography variant="subtitle1" gutterBottom>
        Feed-back Signals for S&OP
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
        Execution outcome signals that suggest re-tuning S&OP policy parameters.
      </Typography>
      <FeedbackSignalCards configId={configId} fedBackTo="sop" />
    </Box>
  );

  // -----------------------------------------------------------------------
  // Render: Tab 3 -- Lineage
  // -----------------------------------------------------------------------

  const renderLineageTab = () => (
    <Box>
      <Typography variant="subtitle1" gutterBottom>
        Policy Envelope Lineage
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
        Hash-chain lineage showing upstream sources and downstream dependents of the current
        Policy Envelope.
      </Typography>
      {currentEnvelopeId ? (
        <ArtifactLineage artifactType="policy_envelope" artifactId={currentEnvelopeId} />
      ) : (
        <Paper variant="outlined" sx={{ p: 3, textAlign: 'center' }}>
          <Typography variant="body2" color="text.secondary">
            No Policy Envelope loaded. Save a Policy Envelope first to view lineage.
          </Typography>
        </Paper>
      )}
    </Box>
  );

  // -----------------------------------------------------------------------
  // Main render
  // -----------------------------------------------------------------------

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" p={6}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3 }}>
      {/* Page header */}
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={2}>
        <Box>
          <Typography variant="h5">S&OP Policy Envelope</Typography>
          <Typography variant="body2" color="text.secondary">
            Define or review the policy parameters that govern the planning cascade.
          </Typography>
        </Box>
        {currentEnvelopeId && (
          <Chip
            label={`Envelope ID: ${currentEnvelopeId}`}
            variant="outlined"
            size="small"
          />
        )}
      </Box>

      <Divider sx={{ mb: 2 }} />

      {/* Tabs */}
      <Paper variant="outlined" sx={{ mb: 2 }}>
        <Tabs
          value={activeTab}
          onChange={(_, newValue) => setActiveTab(newValue)}
          variant="fullWidth"
        >
          <Tab label="Input / Review" />
          <Tab label="Feed-back" />
          <Tab label="Lineage" />
        </Tabs>
      </Paper>

      {/* Tab panels */}
      <Box sx={{ mt: 2 }}>
        {activeTab === 0 && renderInputReviewTab()}
        {activeTab === 1 && renderFeedbackTab()}
        {activeTab === 2 && renderLineageTab()}
      </Box>
    </Box>
  );
};

export default SOPPolicyPage;
