import React, { useState, useEffect, useCallback } from 'react';
import { api } from '../../services/api';
import { cn } from '@azirella-ltd/autonomy-frontend';
import {
  Card, CardContent, CardHeader, CardTitle, Badge, Button, Alert, AlertDescription, Spinner,
} from '../../components/common';
import { AlertTriangle, Info, RefreshCw, CheckCircle2 } from 'lucide-react';

// Aligned with app.models.tms_planning.PlanVersion
const PLAN_VERSIONS = [
  {
    key: 'constrained_live',
    label: 'Constrained — Live',
    short: 'Live',
    color: 'border-blue-500 bg-blue-50 text-blue-700',
    description: 'The plan currently driving execution. Today this is a decision record assembled from agent actions (not a true constrained plan). See Phase 3 of the re-architecture.',
  },
  {
    key: 'unconstrained_reference',
    label: 'Unconstrained — Reference',
    short: 'Unconstrained',
    color: 'border-purple-500 bg-purple-50 text-purple-700',
    description: 'Ideal plan if carrier capacity, equipment, and dock slots were unlimited. Not yet produced — arrives with Phase 1 (Unconstrained Movement Planner).',
  },
  {
    key: 'erp_baseline',
    label: 'ERP Baseline',
    short: 'ERP',
    color: 'border-gray-400 bg-gray-50 text-gray-700',
    description: 'The external TMS or ERP plan, for comparison. Populated by the ERP extractors when a customer is connected to SAP TM / Oracle OTM / Blue Yonder.',
  },
  {
    key: 'decision_action',
    label: 'Decision Action',
    short: 'Override',
    color: 'border-amber-500 bg-amber-50 text-amber-700',
    description: 'User-authored override layered on top of the live plan. Comes from the Decision Stream override flow.',
  },
];

function PlanCard({ plan }) {
  return (
    <Card variant="outline">
      <CardContent className="p-4 space-y-2">
        <div className="flex items-center justify-between">
          <span className="font-semibold text-sm truncate">
            {plan.plan_name || `Plan #${plan.id}`}
          </span>
          <Badge className={cn('text-[10px]')}>{plan.status}</Badge>
        </div>
        <div className="text-xs text-gray-600">
          {plan.plan_start_date} → {plan.plan_end_date}
        </div>
        <div className="grid grid-cols-3 gap-2 text-xs pt-1 border-t">
          <div>
            <div className="text-gray-500">Loads</div>
            <div className="font-medium">{plan.total_planned_loads ?? '—'}</div>
          </div>
          <div>
            <div className="text-gray-500">Shipments</div>
            <div className="font-medium">{plan.total_planned_shipments ?? '—'}</div>
          </div>
          <div>
            <div className="text-gray-500">Util %</div>
            <div className="font-medium">
              {plan.avg_utilization_pct != null
                ? `${plan.avg_utilization_pct.toFixed(1)}%`
                : '—'}
            </div>
          </div>
        </div>
        <div className="text-[10px] text-gray-400 pt-1">
          Generated by {plan.generated_by || plan.optimization_method || '—'}
        </div>
      </CardContent>
    </Card>
  );
}

export default function TransportationPlanView() {
  const [selectedVersion, setSelectedVersion] = useState('constrained_live');
  const [plans, setPlans] = useState([]);
  const [meta, setMeta] = useState({ counts_by_version: {}, planning_is_constrained: false });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const loadPlans = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const r = await api.get('/transportation-plans', {
        params: { plan_version: selectedVersion, limit: 50 },
      });
      setPlans(r.data.items || []);
      setMeta({
        counts_by_version: r.data.counts_by_version || {},
        planning_is_constrained: r.data.planning_is_constrained ?? false,
        supported_versions: r.data.supported_versions || [],
      });
    } catch (e) {
      setError(e?.response?.data?.detail || e.message);
      setPlans([]);
    } finally {
      setLoading(false);
    }
  }, [selectedVersion]);

  useEffect(() => { loadPlans(); }, [loadPlans]);

  const activeVersion = PLAN_VERSIONS.find(v => v.key === selectedVersion) || PLAN_VERSIONS[0];

  return (
    <div className="p-6 space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold">Transportation Plan</h2>
          <p className="text-sm text-muted-foreground">
            The four named views from the Tactical Planning Re-Architecture. Today only
            <span className="font-medium"> Constrained — Live </span>is populated.
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={loadPlans} disabled={loading} className="gap-1">
          <RefreshCw className={cn('h-4 w-4', loading && 'animate-spin')} />
          Refresh
        </Button>
      </div>

      {/* Honesty banner — flip to green CheckCircle when PLANNING_IS_CONSTRAINED=True (Phase 3) */}
      {!meta.planning_is_constrained && (
        <Alert variant="default" className="border-amber-300 bg-amber-50">
          <AlertTriangle className="h-4 w-4 text-amber-600" />
          <AlertDescription className="text-amber-900 text-sm">
            <strong>Planning is not yet constrained.</strong> The "Live" plan below is a decision
            record assembled from agent actions — the Integrated Balancer (Phase 3) is not yet
            online. See <code>docs/TACTICAL_PLANNING_REARCHITECTURE.md</code>.
          </AlertDescription>
        </Alert>
      )}
      {meta.planning_is_constrained && (
        <Alert variant="default" className="border-green-300 bg-green-50">
          <CheckCircle2 className="h-4 w-4 text-green-600" />
          <AlertDescription className="text-green-900 text-sm">
            Integrated Balancer is online. The "Live" plan is a real constrained plan.
          </AlertDescription>
        </Alert>
      )}

      {/* Toggle */}
      <div className="flex flex-wrap gap-2">
        {PLAN_VERSIONS.map(v => {
          const count = meta.counts_by_version?.[v.key] ?? 0;
          const isActive = v.key === selectedVersion;
          return (
            <button
              key={v.key}
              onClick={() => setSelectedVersion(v.key)}
              className={cn(
                'px-3 py-2 rounded-md border text-sm transition-colors',
                isActive
                  ? v.color + ' border-2'
                  : 'border-gray-200 hover:border-gray-300 bg-white text-gray-600',
              )}
            >
              <div className="font-medium">{v.short}</div>
              <div className="text-[10px] opacity-70">{count} plan{count === 1 ? '' : 's'}</div>
            </button>
          );
        })}
      </div>

      <Card variant="outline" className="bg-gray-50">
        <CardContent className="p-3 text-sm text-gray-700 flex items-start gap-2">
          <Info className="h-4 w-4 mt-0.5 flex-shrink-0 text-blue-500" />
          <span>{activeVersion.description}</span>
        </CardContent>
      </Card>

      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {loading ? (
        <div className="flex items-center gap-2 text-sm text-gray-500">
          <Spinner /> Loading plans…
        </div>
      ) : plans.length === 0 ? (
        <Alert>
          <AlertDescription>
            No <strong>{activeVersion.label}</strong> plans yet for this tenant.{' '}
            {selectedVersion === 'unconstrained_reference' &&
              'Arrives with Phase 1 (Unconstrained Movement Planner).'}
            {selectedVersion === 'erp_baseline' &&
              'Connect an external TMS (SAP TM / Oracle OTM / Blue Yonder) via ERP + TMS Integrations to populate this view.'}
            {selectedVersion === 'decision_action' &&
              'Override a live plan from the Decision Stream to populate this view.'}
          </AlertDescription>
        </Alert>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {plans.map(p => <PlanCard key={p.id} plan={p} />)}
        </div>
      )}
    </div>
  );
}
