-- Add missing columns to users table
ALTER TABLE users
ADD COLUMN last_login DATETIME DEFAULT NULL,
ADD COLUMN last_password_change DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN failed_login_attempts INT DEFAULT 0,
ADD COLUMN locked_until DATETIME DEFAULT NULL,
ADD COLUMN mfa_secret VARCHAR(100) DEFAULT NULL,
ADD COLUMN mfa_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
