#!/usr/bin/env python3
"""
Train TMS TRM Models via Behavioral Cloning

Trains one PyTorch MLP per TRM from the jsonl/parquet corpus generated by
generate_tms_corpus.py. Uses CrossEntropyLoss (not MSE) since TRM actions
are discrete classifications, not continuous values.

Architecture per TRM:
    Input: state feature vector (float32, variable dim per TRM)
    Hidden: 2× dense layers (128, 64) with ReLU + dropout
    Output: logits over action classes (variable per TRM)

Saves checkpoints to training_data/checkpoints/trm_{name}_bc_v1.pt
in the format expected by Core's PretrainedTrmRegistry.

Usage:
    python scripts/pretraining/train_tms_trms.py --trm capacity_promise
    python scripts/pretraining/train_tms_trms.py --all
    python scripts/pretraining/train_tms_trms.py --all --epochs 200 --lr 1e-3
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from dataclasses import fields as dc_fields
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import numpy as np

BACKEND_ROOT = Path(__file__).resolve().parents[2]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("train_tms_trms")

# Action name → index mapping (must match generate_tms_corpus.py)
ACTION_NAMES = {
    "ACCEPT": 0, "REJECT": 1, "DEFER": 2, "ESCALATE": 3,
    "MODIFY": 4, "RETENDER": 5, "REROUTE": 6, "CONSOLIDATE": 7,
    "SPLIT": 8, "REPOSITION": 9, "HOLD": 10,
}
NUM_ACTIONS = len(ACTION_NAMES)

ALL_TRMS = [
    "capacity_promise", "shipment_tracking", "demand_sensing",
    "capacity_buffer", "exception_management", "freight_procurement",
    "broker_routing", "dock_scheduling", "load_build",
    "intermodal_transfer", "equipment_reposition",
]


# ============================================================================
# Model
# ============================================================================

class TRMClassifier(nn.Module):
    """
    Simple MLP for discrete TRM action classification.

    Input: state feature vector (float32)
    Output: logits over NUM_ACTIONS classes
    """
    def __init__(self, input_dim: int, hidden_dims: Tuple[int, ...] = (128, 64),
                 dropout: float = 0.2):
        super().__init__()
        layers = []
        prev = input_dim
        for h in hidden_dims:
            layers.extend([
                nn.Linear(prev, h),
                nn.ReLU(),
                nn.Dropout(dropout),
            ])
            prev = h
        layers.append(nn.Linear(prev, NUM_ACTIONS))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


# ============================================================================
# Data loading
# ============================================================================

def _is_numeric(val: Any) -> bool:
    if val is None:
        return True  # Will be replaced with 0
    if isinstance(val, (int, float, bool)):
        return True
    if isinstance(val, str):
        try:
            float(val)
            return True
        except (ValueError, TypeError):
            return False
    return False


def load_corpus(
    trm_type: str, corpus_dir: Path
) -> Tuple[np.ndarray, np.ndarray, Set[int], List[str], np.ndarray, np.ndarray]:
    """
    Load corpus from jsonl, extract numeric state features + action labels.
    Returns (features, labels, active_action_set, state_keys, means, stds).

    state_keys / means / stds are persisted in the checkpoint so the
    inference-time state→tensor path can (a) assemble the vector in the
    same column order and (b) apply the same zero-mean / unit-std
    normalization used at training time.
    """
    # Find the corpus file
    candidates = list(corpus_dir.glob(f"{trm_type}_*.jsonl")) + list(corpus_dir.glob(f"{trm_type}_*.parquet"))
    if not candidates:
        raise FileNotFoundError(f"No corpus file for {trm_type} in {corpus_dir}")
    corpus_path = candidates[0]
    logger.info(f"Loading corpus: {corpus_path}")

    rows = []
    if corpus_path.suffix == ".jsonl":
        with open(corpus_path) as f:
            for line in f:
                rows.append(json.loads(line))
    else:
        import pyarrow.parquet as pq
        table = pq.read_table(corpus_path)
        rows = table.to_pylist()

    if not rows:
        raise ValueError(f"Empty corpus for {trm_type}")

    # Identify numeric feature columns (state_* + derived_*) from first row
    state_keys = sorted(k for k in rows[0] if (k.startswith("state_") or k.startswith("derived_")) and _is_numeric(rows[0][k]))
    logger.info(f"  {len(state_keys)} numeric state features, {len(rows)} samples")

    # Extract features + labels
    features = np.zeros((len(rows), len(state_keys)), dtype=np.float32)
    labels = np.zeros(len(rows), dtype=np.int64)
    active_actions: Set[int] = set()

    for i, row in enumerate(rows):
        for j, key in enumerate(state_keys):
            val = row.get(key)
            if val is None or val == "":
                features[i, j] = 0.0
            elif isinstance(val, bool):
                features[i, j] = float(val)
            elif isinstance(val, (int, float)):
                features[i, j] = float(val)
            elif isinstance(val, str):
                try:
                    features[i, j] = float(val)
                except (ValueError, TypeError):
                    features[i, j] = 0.0
            else:
                features[i, j] = 0.0
        labels[i] = row["action"]
        active_actions.add(row["action"])

    # Normalize features (zero-mean, unit-std per column)
    means = features.mean(axis=0)
    stds = features.std(axis=0)
    stds[stds < 1e-8] = 1.0
    features = (features - means) / stds

    logger.info(f"  Active actions: {sorted(active_actions)} ({len(active_actions)} classes)")
    return features, labels, active_actions, state_keys, means, stds


# ============================================================================
# Training
# ============================================================================

def train_trm(
    trm_type: str,
    corpus_dir: Path,
    checkpoint_dir: Path,
    epochs: int = 100,
    batch_size: int = 256,
    lr: float = 1e-3,
    val_split: float = 0.15,
    device: str = "auto",
) -> Dict[str, Any]:
    """Train one TRM and save checkpoint."""
    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"Training {trm_type} on {device}")

    features, labels, active_actions, state_keys, feat_means, feat_stds = load_corpus(
        trm_type, corpus_dir
    )
    n_samples, input_dim = features.shape

    # Train/val split
    n_val = int(n_samples * val_split)
    indices = np.random.permutation(n_samples)
    val_idx, train_idx = indices[:n_val], indices[n_val:]

    X_train = torch.tensor(features[train_idx], dtype=torch.float32).to(device)
    y_train = torch.tensor(labels[train_idx], dtype=torch.long).to(device)
    X_val = torch.tensor(features[val_idx], dtype=torch.float32).to(device)
    y_val = torch.tensor(labels[val_idx], dtype=torch.long).to(device)

    # Class weights for imbalanced datasets (DemandSensing, CapacityBuffer)
    class_counts = np.bincount(labels, minlength=NUM_ACTIONS).astype(np.float32)
    class_counts[class_counts == 0] = 1.0
    class_weights = (1.0 / class_counts) * n_samples / NUM_ACTIONS
    class_weights = torch.tensor(class_weights, dtype=torch.float32).to(device)

    model = TRMClassifier(input_dim=input_dim).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=10, factor=0.5)

    train_ds = TensorDataset(X_train, y_train)
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

    best_val_acc = 0.0
    best_epoch = 0
    best_state = None
    train_losses = []

    t0 = time.time()
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()
            logits = model(X_batch)
            loss = criterion(logits, y_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * len(X_batch)
        epoch_loss /= len(X_train)
        train_losses.append(epoch_loss)

        # Validation
        model.eval()
        with torch.no_grad():
            val_logits = model(X_val)
            val_preds = val_logits.argmax(dim=1)
            val_acc = (val_preds == y_val).float().mean().item()
            val_loss = criterion(val_logits, y_val).item()

        scheduler.step(val_loss)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_epoch = epoch
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

        if (epoch + 1) % 20 == 0 or epoch == 0:
            logger.info(f"  Epoch {epoch+1}/{epochs}: loss={epoch_loss:.4f} val_acc={val_acc:.4f} val_loss={val_loss:.4f} lr={optimizer.param_groups[0]['lr']:.2e}")

    elapsed = time.time() - t0
    logger.info(f"  Best val_acc={best_val_acc:.4f} at epoch {best_epoch+1} ({elapsed:.1f}s)")

    # Per-class accuracy on validation set
    model.load_state_dict(best_state)
    model.eval()
    with torch.no_grad():
        val_preds = model(X_val).argmax(dim=1)
    per_class = {}
    for action_name, action_idx in ACTION_NAMES.items():
        mask = y_val == action_idx
        if mask.sum() > 0:
            acc = (val_preds[mask] == action_idx).float().mean().item()
            per_class[action_name] = {"accuracy": round(acc, 4), "count": int(mask.sum())}

    # Save checkpoint
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    ckpt_path = checkpoint_dir / f"trm_{trm_type}_bc_v1.pt"
    torch.save({
        "model_state_dict": best_state,
        "trm_type": trm_type,
        "input_dim": input_dim,
        "hidden_dims": (128, 64),
        "num_actions": NUM_ACTIONS,
        "best_val_acc": best_val_acc,
        "best_epoch": best_epoch,
        "epochs_trained": epochs,
        "per_class_accuracy": per_class,
        "active_actions": sorted(active_actions),
        # Inference-time stats — must match load_corpus() column ordering.
        # bc_checkpoint_loader.load_bc_checkpoint() verifies these are present.
        "feature_keys": state_keys,
        "feature_means": feat_means.tolist(),
        "feature_stds": feat_stds.tolist(),
        "training_config": {
            "lr": lr, "batch_size": batch_size, "val_split": val_split,
            "class_weighted": True, "optimizer": "Adam",
        },
    }, ckpt_path)
    logger.info(f"  Saved: {ckpt_path} ({ckpt_path.stat().st_size / 1024:.0f} KB)")

    return {
        "trm_type": trm_type,
        "val_acc": best_val_acc,
        "best_epoch": best_epoch,
        "per_class": per_class,
        "input_dim": input_dim,
        "samples": n_samples,
        "elapsed_s": elapsed,
    }


# ============================================================================
# Entry point
# ============================================================================

def main():
    ap = argparse.ArgumentParser(description="Train TMS TRM models via behavioral cloning")
    ap.add_argument("--trm", type=str, default=None, choices=ALL_TRMS)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--batch-size", type=int, default=256)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--corpus-dir", type=str, default=None)
    ap.add_argument("--checkpoint-dir", type=str, default=None)
    ap.add_argument("--device", type=str, default="auto")
    args = ap.parse_args()

    if not args.trm and not args.all:
        ap.error("Specify --trm <name> or --all")

    trms = ALL_TRMS if args.all else [args.trm]
    corpus_dir = Path(args.corpus_dir) if args.corpus_dir else Path(BACKEND_ROOT) / "training_data" / "tms_corpus"
    checkpoint_dir = Path(args.checkpoint_dir) if args.checkpoint_dir else Path(BACKEND_ROOT) / "training_data" / "checkpoints"

    logger.info(f"Training {len(trms)} TRMs, {args.epochs} epochs, device={args.device}")
    results = []
    for trm in trms:
        try:
            r = train_trm(trm, corpus_dir, checkpoint_dir,
                          epochs=args.epochs, batch_size=args.batch_size,
                          lr=args.lr, device=args.device)
            results.append(r)
        except Exception as e:
            logger.error(f"FAILED {trm}: {e}")
            results.append({"trm_type": trm, "error": str(e)})

    # Summary
    logger.info("\n=== TRAINING SUMMARY ===")
    for r in results:
        if "error" in r:
            logger.info(f"  {r['trm_type']}: FAILED — {r['error']}")
        else:
            logger.info(f"  {r['trm_type']}: val_acc={r['val_acc']:.4f} (epoch {r['best_epoch']+1}, {r['elapsed_s']:.0f}s, {r['input_dim']}→{NUM_ACTIONS})")


if __name__ == "__main__":
    main()
