"""
S&OP Service

Manages S&OP policy parameters (Policy Envelope).
Supports two modes:
- FULL: Autonomy generates optimized parameters via simulation
- INPUT: Customer provides parameters from their existing S&OP process

The same UI screens work in both modes - what changes is the source of values.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple
from enum import Enum
from datetime import date, datetime
import logging

from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)


class SOPMode(Enum):
    """Operating mode for S&OP service"""
    FULL = "full"      # Autonomy simulation generates parameters
    INPUT = "input"    # Customer provides parameters manually


@dataclass
class ServiceTierTarget:
    """Service level target for a customer segment"""
    segment: str
    otif_floor: float
    fill_rate_target: float = 0.98
    lead_time_days: int = 2


@dataclass
class CategoryPolicy:
    """Policy parameters for a product category"""
    category: str
    safety_stock_wos: float  # Weeks of supply
    dos_ceiling: int  # Max days of supply
    expedite_cap: float  # $ cap on expedite per month
    holding_cost_rate: float = 0.25


@dataclass
class SupplierConstraint:
    """Supplier concentration constraint"""
    supplier_id: str
    max_share: float  # Maximum % of category


@dataclass
class SOPParameters:
    """
    S&OP Policy Parameters (Policy Envelope)

    These are the tunable parameters that govern downstream agents.
    Can be generated by simulation (FULL) or entered manually (INPUT).
    """
    # Service tier targets
    service_tiers: List[ServiceTierTarget] = field(default_factory=list)

    # Category policies
    category_policies: List[CategoryPolicy] = field(default_factory=list)

    # Supplier constraints
    supplier_constraints: List[SupplierConstraint] = field(default_factory=list)

    # Financial guardrails
    total_inventory_cap: Optional[float] = None
    gmroi_target: float = 3.0
    max_expedite_total: Optional[float] = None

    # Effective period
    effective_date: date = field(default_factory=date.today)

    def to_policy_envelope_dict(self) -> Dict[str, Any]:
        """Convert to format for PolicyEnvelope model"""
        return {
            "safety_stock_targets": {
                p.category: p.safety_stock_wos for p in self.category_policies
            },
            "otif_floors": {
                t.segment: t.otif_floor for t in self.service_tiers
            },
            "allocation_reserves": {
                t.segment: 0.30 if t.segment == "strategic" else 0.20
                for t in self.service_tiers
            },
            "expedite_caps": {
                p.category: p.expedite_cap for p in self.category_policies
            },
            "dos_ceilings": {
                p.category: p.dos_ceiling for p in self.category_policies
            },
            "supplier_concentration_limits": {
                c.supplier_id: c.max_share for c in self.supplier_constraints
            },
            "total_inventory_cap": self.total_inventory_cap,
            "gmroi_target": self.gmroi_target,
            "effective_date": self.effective_date,
        }


@dataclass
class WhatIfScenario:
    """What-if scenario for S&OP simulation (FULL mode only)"""
    name: str
    parameter_changes: Dict[str, Any]
    # Results populated after simulation
    projected_otif: Optional[float] = None
    projected_inventory_investment: Optional[float] = None
    projected_expedite_cost: Optional[float] = None
    projected_gmroi: Optional[float] = None


class SOPService:
    """
    S&OP Service

    Manages S&OP policy parameters and simulation.

    In FULL mode:
    - Runs Monte Carlo simulation to optimize parameters
    - Generates what-if scenarios
    - Provides confidence intervals

    In INPUT mode:
    - Accepts customer-provided parameters
    - Validates against constraints
    - Same UI, different source of values
    """

    def __init__(self, db: Session, mode: SOPMode = SOPMode.INPUT):
        """
        Initialize S&OP service.

        Args:
            db: Database session
            mode: FULL (simulation) or INPUT (manual)
        """
        self.db = db
        self.mode = mode

    def create_policy_envelope(
        self,
        config_id: int,
        group_id: int,
        params: SOPParameters,
        user_id: Optional[int] = None,
    ) -> Dict[str, Any]:
        """
        Create a new policy envelope.

        In FULL mode: Runs simulation first.
        In INPUT mode: Uses provided parameters directly.

        Args:
            config_id: Supply chain config ID
            group_id: Group/company ID
            params: S&OP parameters
            user_id: User creating the envelope

        Returns:
            Created PolicyEnvelope as dict
        """
        from app.models.planning_cascade import PolicyEnvelope, PolicySource

        if self.mode == SOPMode.FULL:
            # Run simulation to optimize/validate parameters
            simulation_result = self._run_sop_simulation(config_id, params)
            generated_by = PolicySource.AUTONOMY_SIM
        else:
            simulation_result = None
            generated_by = PolicySource.CUSTOMER_INPUT

        # Build envelope data
        envelope_data = params.to_policy_envelope_dict()

        envelope = PolicyEnvelope(
            config_id=config_id,
            group_id=group_id,
            generated_by=generated_by,
            safety_stock_targets=envelope_data["safety_stock_targets"],
            otif_floors=envelope_data["otif_floors"],
            allocation_reserves=envelope_data["allocation_reserves"],
            expedite_caps=envelope_data["expedite_caps"],
            dos_ceilings=envelope_data["dos_ceilings"],
            supplier_concentration_limits=envelope_data["supplier_concentration_limits"],
            total_inventory_cap=envelope_data["total_inventory_cap"],
            gmroi_target=envelope_data["gmroi_target"],
            effective_date=envelope_data["effective_date"],
            created_by=user_id,
        )

        # Add simulation metadata if in FULL mode
        if simulation_result:
            envelope.simulation_run_id = simulation_result.get("run_id")
            envelope.what_if_scenarios = simulation_result.get("what_if_scenarios")
            envelope.confidence_intervals = simulation_result.get("confidence_intervals")

        # Compute hash
        envelope.hash = envelope.compute_hash()

        self.db.add(envelope)
        self.db.commit()
        self.db.refresh(envelope)

        logger.info(f"Created policy envelope {envelope.hash[:8]} in {self.mode.value} mode")

        return self._envelope_to_dict(envelope)

    def get_active_envelope(
        self,
        config_id: int,
        as_of_date: Optional[date] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Get the active policy envelope for a config.

        Args:
            config_id: Supply chain config ID
            as_of_date: Date to check (defaults to today)

        Returns:
            Active PolicyEnvelope as dict, or None
        """
        from app.models.planning_cascade import PolicyEnvelope

        check_date = as_of_date or date.today()

        envelope = self.db.query(PolicyEnvelope).filter(
            PolicyEnvelope.config_id == config_id,
            PolicyEnvelope.effective_date <= check_date,
        ).order_by(
            PolicyEnvelope.effective_date.desc()
        ).first()

        if envelope:
            return self._envelope_to_dict(envelope)
        return None

    def run_what_if_scenario(
        self,
        config_id: int,
        base_params: SOPParameters,
        scenario: WhatIfScenario
    ) -> WhatIfScenario:
        """
        Run a what-if scenario (FULL mode only).

        Simulates the impact of parameter changes.

        Args:
            config_id: Supply chain config ID
            base_params: Base S&OP parameters
            scenario: What-if scenario to simulate

        Returns:
            Scenario with results populated
        """
        if self.mode != SOPMode.FULL:
            raise ValueError("What-if scenarios only available in FULL mode")

        # Apply parameter changes to base
        modified_params = self._apply_parameter_changes(base_params, scenario.parameter_changes)

        # Run simulation
        result = self._run_sop_simulation(config_id, modified_params)

        # Populate scenario results
        scenario.projected_otif = result.get("expected_otif")
        scenario.projected_inventory_investment = result.get("expected_inventory_$")
        scenario.projected_expedite_cost = result.get("expected_expedite_$")
        scenario.projected_gmroi = result.get("expected_gmroi")

        return scenario

    def validate_parameters(
        self,
        params: SOPParameters,
        config_id: int
    ) -> Tuple[bool, List[str]]:
        """
        Validate S&OP parameters against constraints.

        Args:
            params: Parameters to validate
            config_id: Supply chain config for context

        Returns:
            (is_valid, list of error messages)
        """
        errors = []

        # Validate service tiers
        for tier in params.service_tiers:
            if tier.otif_floor < 0 or tier.otif_floor > 1:
                errors.append(f"Invalid OTIF floor for {tier.segment}: {tier.otif_floor}")
            if tier.otif_floor < 0.85:
                errors.append(f"OTIF floor for {tier.segment} below minimum (85%)")

        # Validate category policies
        for policy in params.category_policies:
            if policy.safety_stock_wos < 0:
                errors.append(f"Negative safety stock for {policy.category}")
            if policy.safety_stock_wos > 12:
                errors.append(f"Safety stock for {policy.category} exceeds 12 weeks")
            if policy.dos_ceiling < policy.safety_stock_wos * 7:
                errors.append(f"DOS ceiling for {policy.category} below safety stock")

        # Validate supplier constraints
        total_share = sum(c.max_share for c in params.supplier_constraints)
        if total_share < 1.0:
            logger.warning(f"Supplier concentration limits sum to {total_share} (<100%)")

        return len(errors) == 0, errors

    def get_feed_back_signals(
        self,
        config_id: int,
        since: Optional[datetime] = None
    ) -> List[Dict[str, Any]]:
        """
        Get feed-back signals that should re-tune S&OP parameters.

        These come from downstream execution outcomes.

        Args:
            config_id: Supply chain config ID
            since: Only get signals since this time

        Returns:
            List of feed-back signals
        """
        from app.models.planning_cascade import FeedBackSignal

        query = self.db.query(FeedBackSignal).filter(
            FeedBackSignal.config_id == config_id,
            FeedBackSignal.fed_back_to.in_(["sop", "supply_agent"]),
            FeedBackSignal.acknowledged == False,
        )

        if since:
            query = query.filter(FeedBackSignal.measured_at >= since)

        signals = query.order_by(FeedBackSignal.measured_at.desc()).all()

        return [
            {
                "id": s.id,
                "signal_type": s.signal_type,
                "metric_name": s.metric_name,
                "metric_value": s.metric_value,
                "threshold": s.threshold,
                "deviation": s.deviation,
                "details": s.details,
                "suggested_retune": s.suggested_retune,
                "measured_at": s.measured_at.isoformat(),
            }
            for s in signals
        ]

    def apply_suggested_retune(
        self,
        signal_id: int,
        user_id: int
    ) -> Dict[str, Any]:
        """
        Apply a suggested parameter re-tune from a feed-back signal.

        Args:
            signal_id: Feed-back signal ID
            user_id: User applying the change

        Returns:
            Updated policy envelope
        """
        from app.models.planning_cascade import FeedBackSignal

        signal = self.db.query(FeedBackSignal).filter_by(id=signal_id).first()
        if not signal:
            raise ValueError(f"Signal {signal_id} not found")

        if not signal.suggested_retune:
            raise ValueError("Signal has no suggested re-tune")

        # Get current envelope
        envelope_dict = self.get_active_envelope(signal.config_id)
        if not envelope_dict:
            raise ValueError("No active policy envelope")

        # Apply the suggested change
        # This is simplified - real implementation would be more sophisticated
        logger.info(f"Applying suggested retune: {signal.suggested_retune}")

        # Mark signal as actioned
        signal.actioned = True
        signal.actioned_at = datetime.utcnow()
        signal.actioned_by = user_id
        signal.acknowledged = True

        self.db.commit()

        return envelope_dict

    def _run_sop_simulation(
        self,
        config_id: int,
        params: SOPParameters
    ) -> Dict[str, Any]:
        """
        Run S&OP Monte Carlo simulation.

        Simulates the full planning cascade to evaluate parameter impact.
        """
        # This would integrate with monte_carlo_planner.py
        # For now, return mock results
        logger.info(f"Running S&OP simulation for config {config_id}")

        return {
            "run_id": 1,
            "expected_otif": 0.96,
            "expected_inventory_$": 1850000,
            "expected_expedite_$": 12000,
            "expected_gmroi": 3.2,
            "confidence_intervals": {
                "otif_p10": 0.93,
                "otif_p50": 0.96,
                "otif_p90": 0.98,
                "inventory_p10": 1650000,
                "inventory_p50": 1850000,
                "inventory_p90": 2100000,
            },
            "what_if_scenarios": [],
        }

    def _apply_parameter_changes(
        self,
        base: SOPParameters,
        changes: Dict[str, Any]
    ) -> SOPParameters:
        """Apply what-if parameter changes to base parameters"""
        # Deep copy and apply changes
        # Simplified implementation
        return base

    def _envelope_to_dict(self, envelope) -> Dict[str, Any]:
        """Convert PolicyEnvelope to dict"""
        return {
            "id": envelope.id,
            "hash": envelope.hash,
            "config_id": envelope.config_id,
            "group_id": envelope.group_id,
            "generated_by": envelope.generated_by.value,
            "safety_stock_targets": envelope.safety_stock_targets,
            "otif_floors": envelope.otif_floors,
            "allocation_reserves": envelope.allocation_reserves,
            "expedite_caps": envelope.expedite_caps,
            "dos_ceilings": envelope.dos_ceilings,
            "supplier_concentration_limits": envelope.supplier_concentration_limits,
            "total_inventory_cap": envelope.total_inventory_cap,
            "gmroi_target": envelope.gmroi_target,
            "effective_date": envelope.effective_date.isoformat(),
            "simulation_run_id": envelope.simulation_run_id,
            "what_if_scenarios": envelope.what_if_scenarios,
            "confidence_intervals": envelope.confidence_intervals,
            "created_at": envelope.created_at.isoformat() if envelope.created_at else None,
        }


def create_default_sop_parameters_for_food_dist() -> SOPParameters:
    """
    Create default S&OP parameters for Food Dist distributor.

    Based on the Food Dist config with:
    - 5 temperature categories
    - 3 customer segments
    - 10 suppliers
    """
    return SOPParameters(
        service_tiers=[
            ServiceTierTarget(segment="strategic", otif_floor=0.99, fill_rate_target=0.99),
            ServiceTierTarget(segment="standard", otif_floor=0.95, fill_rate_target=0.98),
            ServiceTierTarget(segment="transactional", otif_floor=0.90, fill_rate_target=0.95),
        ],
        category_policies=[
            CategoryPolicy(
                category="frozen_proteins",
                safety_stock_wos=2.0,
                dos_ceiling=21,
                expedite_cap=15000,
                holding_cost_rate=0.30,  # Higher for frozen
            ),
            CategoryPolicy(
                category="refrigerated_dairy",
                safety_stock_wos=1.5,
                dos_ceiling=14,
                expedite_cap=10000,
                holding_cost_rate=0.28,
            ),
            CategoryPolicy(
                category="dry_pantry",
                safety_stock_wos=3.0,
                dos_ceiling=45,
                expedite_cap=5000,
                holding_cost_rate=0.20,
            ),
            CategoryPolicy(
                category="frozen_desserts",
                safety_stock_wos=2.0,
                dos_ceiling=28,
                expedite_cap=8000,
                holding_cost_rate=0.30,
            ),
            CategoryPolicy(
                category="beverages",
                safety_stock_wos=2.5,
                dos_ceiling=35,
                expedite_cap=6000,
                holding_cost_rate=0.18,
            ),
        ],
        supplier_constraints=[
            SupplierConstraint(supplier_id="Tyson", max_share=0.40),
            SupplierConstraint(supplier_id="Hormel", max_share=0.35),
            SupplierConstraint(supplier_id="Kraft", max_share=0.35),
            SupplierConstraint(supplier_id="General_Mills", max_share=0.30),
            SupplierConstraint(supplier_id="PepsiCo", max_share=0.40),
        ],
        total_inventory_cap=2500000,
        gmroi_target=3.0,
        max_expedite_total=50000,
    )
